INC = -I../bm-3.20.0/src

s1:
	g++ -march=native -g -O3 -std=c++17 $(INC) sample1.cpp -o sample1

s2:
	g++ -march=native -g -O3 -std=c++17 $(INC) sample2.cpp -o sample2

s3:
	g++ -march=native -g -O3 -std=c++17 $(INC) sample3.cpp -o sample3
