BitMagic-C++: bm::decoder_base Class Reference
bm::decoder_base Class Reference
Elias Gamma Code (internal)
Base class for all decoding functionality.
#include <encoding.h>
Public Member Functions
decoder_base (const unsigned char *buf)
unsigned char get_8 ()
Reads character from the decoding buffer.
unsigned size () const
Returns size of the current decoding stream.
void seek (int delta)
change current position
void memcpy (unsigned char *dst, size_t count)
read bytes from the decode buffer
const unsigned char * get_pos () const
Return current buffer pointer.
Protected Attributes
const unsigned char * buf_
const unsigned char * start_
Detailed Description
Base class for all decoding functionality.
Definition at line 74 of file encoding.h.
Constructor & Destructor Documentation
decoder_base()
bm::decoder_base::decoder_base (const unsigned char * buf) inline
Definition at line 77 of file encoding.h.
Member Function Documentation
get_8()
unsigned char bm::decoder_base::get_8 () inline
Reads character from the decoding buffer.
Definition at line 80 of file encoding.h.
Referenced by bm::sparse_vector_deserializer< SV >::deserialize(), bm::compressed_collection_deserializer< CBC >::deserialize(), bm::deserializer< typename SV::bvector_type, bm::decoder >::deserialize(), bm::operation_deserializer< BV >::deserialize(), and bm::deserialize().
get_pos()
const unsigned char* bm::decoder_base::get_pos () const inline
Return current buffer pointer.
Definition at line 92 of file encoding.h.
Referenced by bm::compressed_collection_deserializer< CBC >::deserialize().
memcpy()
void bm::decoder_base::memcpy (unsigned char * dst, size_t count) inline
read bytes from the decode buffer
Load bytes from the decode buffer
Definition at line 773 of file encoding.h.
References bm::encoder::memcpy().
Referenced by bm::sparse_vector_deserializer< SV >::deserialize(), bm::compressed_collection_deserializer< CBC >::deserialize(), and bm::decoder::get_32().
seek()
void bm::decoder_base::seek (int delta) inline
change current position
Definition at line 86 of file encoding.h.
References bm::encoder::memcpy().
Referenced by bm::compressed_collection_deserializer< CBC >::deserialize(), bm::decoder::get_16(), bm::decoder_little_endian::get_16(), bm::decoder::get_32(), bm::decoder_little_endian::get_32(), bm::decoder::get_32_AND(), bm::decoder::get_32_OR(), and bm::decoder_little_endian::get_32_OR().
size()
unsigned bm::decoder_base::size () const inline
Returns size of the current decoding stream.
Definition at line 83 of file encoding.h.
Referenced by bm::deserializer< typename SV::bvector_type, bm::decoder >::deserialize().
Field Documentation
buf_
const unsigned char* bm::decoder_base::buf_ protected
Definition at line 94 of file encoding.h.
Referenced by bm::decoder::get_16(), bm::decoder_little_endian::get_16(), bm::decoder::get_32(), bm::decoder_little_endian::get_32(), bm::decoder::get_32_AND(), bm::decoder::get_32_OR(), and bm::decoder::get_64().
start_
const unsigned char* bm::decoder_base::start_ protected
Definition at line 95 of file encoding.h.
The documentation for this class was generated from the following file:
encoding.h