BitMagic-C++: bm::sparse_vector< Val, BV > Class Template Reference
bm::sparse_vector< Val, BV > Class Template Reference
BitMagic Library » sparse_vector<>
sparse vector with runtime compression using bit transposition method
#include <bmsparsevec.h>
Data Structures
class back_insert_iterator
Back insert iterator implements buffered insert, faster than generic access assignment.
class const_iterator
Const iterator to traverse the sparse vector.
struct is_remap_support
struct is_rsc_support
class reference
Reference class to access elements via common [] operator.
struct statistics
Public Types
typedef Val value_type
typedef bm::id_t size_type
typedef BV bvector_type
typedef bvector_type * bvector_type_ptr
typedef const bvector_type * bvector_type_const_ptr
typedef const value_type & const_reference
typedef BV::allocator_type allocator_type
typedef bvector_type::allocation_policy allocation_policy_type
typedef bvector_type::enumerator bvector_enumerator_type
typedef allocator_type::allocator_pool_type allocator_pool_type
typedef bm::basic_bmatrix< BV > bmatrix_type
typedef base_sparse_vector< Val, BV, 1 > parent_type
Public Types inherited from bm::base_sparse_vector< Val, BV, 1 >
enum bit_plains
enum vector_capacity
typedef Val value_type
typedef bm::id_t size_type
typedef BV bvector_type
typedef bvector_type * bvector_type_ptr
typedef const bvector_type * bvector_type_const_ptr
typedef const value_type & const_reference
typedef BV::allocator_type allocator_type
typedef bvector_type::allocation_policy allocation_policy_type
typedef bvector_type::enumerator bvector_enumerator_type
typedef allocator_type::allocator_pool_type allocator_pool_type
typedef bm::basic_bmatrix< BV > bmatrix_type
Public Member Functions
void swap (sparse_vector< Val, BV > &sv) BMNOEXEPT
content exchange
void set_allocator_pool (allocator_pool_type *pool_ptr)
Set allocator pool for local (non-threaded) memory cyclic(lots of alloc-free ops) opertations.
Construction and assignment
sparse_vector (bm::null_support null_able=bm::no_null, allocation_policy_type ap=allocation_policy_type(), size_type bv_max_size=bm::id_max, const allocator_type &alloc=allocator_type())
Sparse vector constructor.
sparse_vector (const sparse_vector< Val, BV > &sv)
sparse_vector< Val, BV > & operator= (const sparse_vector< Val, BV > &sv)
sparse_vector (sparse_vector< Val, BV > &&sv) BMNOEXEPT
sparse_vector< Val, BV > & operator= (sparse_vector< Val, BV > &&sv) BMNOEXEPT
~sparse_vector () BMNOEXEPT
Element access
reference operator[] (size_type idx)
Operator to get write access to an element.
value_type operator[] (size_type idx) const
get specified element without bounds checking
value_type at (size_type idx) const
access specified element with bounds checking
value_type get (bm::id_t idx) const
get specified element without bounds checking
void set (size_type idx, value_type v)
set specified element with bounds checking and automatic resize
void inc (size_type idx)
increment specified element by one
void push_back (value_type v)
push value back into vector
void clear (size_type idx, bool set_null=false)
clear specified element with bounds checking and automatic resize
Iterator access
const_iterator begin () const
Provide const iterator access to container content.
const_iterator end () const
Provide const iterator access to the end.
const_iterator get_const_iterator (size_type idx) const
Get const_itertor re-positioned to specific element.
back_insert_iterator get_back_inserter ()
Provide back insert iterator Back insert iterator implements buffered insertion, which is faster, than random access or push_back.
Loading of sparse vector from C-style array
void import (const value_type *arr, size_type arr_size, size_type offset=0)
Import list of elements from a C-style array.
void import_back (const value_type *arr, size_type arr_size)
Import list of elements from a C-style array (pushed back)
Export content to C-style array
size_type decode (value_type *arr, size_type idx_from, size_type dec_size, bool zero_mem=true) const
Bulk export list of elements to a C-style array.
size_type gather (value_type *arr, const size_type *idx, size_type size, bm::sort_order sorted_idx) const
Gather elements to a C-style array.
Clear
void clear () BMNOEXEPT
resize to zero, free memory
sparse_vector< Val, BV > & clear_range (size_type left, size_type right, bool set_null=false)
clear range (assign bit 0 for all plains)
Size, etc
size_type size () const
return size of the vector
bool empty () const
return true if vector is empty
void resize (size_type sz)
resize vector
Comparison
bool equal (const sparse_vector< Val, BV > &sv, bm::null_support null_able=bm::use_null) const
check if another sparse vector has the same content and size
Memory optimization
void optimize (bm::word_t *temp_block=0, typename bvector_type::optmode opt_mode=bvector_type::opt_compress, typename sparse_vector< Val, BV >::statistics *stat=0)
run memory optimization for all vector plains
void optimize_gap_size ()
Optimize sizes of GAP blocks.
void calc_stat (struct sparse_vector< Val, BV >::statistics *st) const
Calculates memory statistics.
Merge, split, partition data
sparse_vector< Val, BV > & join (const sparse_vector< Val, BV > &sv)
join all with another sparse vector using OR operation
sparse_vector< Val, BV > & merge (sparse_vector< Val, BV > &sv)
merge with another sparse vector using OR operation Merge is different from join(), because it borrows data from the source vector, so it gets modified.
void copy_range (const sparse_vector< Val, BV > &sv, size_type left, size_type right)
copy range of values from another sparse vector
void filter (const bvector_type &bv_mask)
Apply value filter, defined by mask vector.
Public Member Functions inherited from bm::base_sparse_vector< Val, BV, 1 >
base_sparse_vector ()
base_sparse_vector (bm::null_support null_able, allocation_policy_type ap, size_type bv_max_size, const allocator_type &alloc)
base_sparse_vector (const base_sparse_vector< Val, BV, MAX_SIZE > &bsv)
base_sparse_vector (base_sparse_vector< Val, BV, MAX_SIZE > &&bsv) BMNOEXEPT
void swap (base_sparse_vector< Val, BV, MAX_SIZE > &bsv) BMNOEXEPT
size_type size () const
void resize (size_type new_size)
void clear_range (size_type left, size_type right, bool set_null)
void clear () BMNOEXEPT
resize to zero, free memory
bool empty () const
void optimize (bm::word_t *temp_block=0, typename bvector_type::optmode opt_mode=bvector_type::opt_compress, typename bvector_type::statistics *stat=0)
run memory optimization for all bit-vector rows
void calc_stat (typename bvector_type::statistics *st) const
Calculates memory statistics.
bool equal (const base_sparse_vector< Val, BV, MAX_SIZE > &sv, bm::null_support null_able=bm::use_null) const
check if another sparse vector has the same content and size
bool is_nullable () const
check if container supports NULL(unassigned) values
const bvector_type * get_null_bvector () const
Get bit-vector of assigned values or NULL (if not constructed that way)
bool is_null (size_type idx) const
test if specified element is NULL
bvector_type_ptr get_plain (unsigned i)
get access to bit-plain, function checks and creates a plain
bvector_type_const_ptr get_plain (unsigned i) const
get read-only access to bit-plain
unsigned effective_plains () const
Number of effective bit-plains in the value type.
bvector_type_ptr plain (unsigned i)
get access to bit-plain as is (can return NULL)
const bvector_type_ptr plain (unsigned i) const
bvector_type * get_null_bvect ()
void free_plain (unsigned i)
free memory in bit-plain
bm::id64_t get_plains_mask (unsigned element_idx) const
Data Fields
friend const_iterator
friend back_insert_iterator
Protected Types
enum octet_plains { sv_octet_plains = sizeof(value_type) }
Protected Member Functions
void set_value (size_type idx, value_type v)
set value without checking boundaries
void set_value_no_null (size_type idx, value_type v)
set value without checking boundaries or support of NULL
void push_back_no_null (value_type v)
push value back into vector without NULL semantics
void resize_internal (size_type sz)
size_type size_internal () const
bool is_remap () const
size_t remap_size () const
const unsigned char * get_remap_buffer () const
unsigned char * init_remap_buffer ()
void set_remap ()
Protected Member Functions inherited from bm::base_sparse_vector< Val, BV, 1 >
void copy_from (const base_sparse_vector< Val, BV, MAX_SIZE > &bsv)
void clear_value_plains_from (unsigned plain_idx, size_type idx)
void insert_clear_value_plains_from (unsigned plain_idx, size_type idx)
Friends
template<class V , class SV >
class rsc_sparse_vector
template<class SVect >
class sparse_vector_scanner
template<class SVect >
class sparse_vector_serializer
template<class SVect >
class sparse_vector_deserializer
Various traits
void set_null (size_type idx)
set specified element to unassigned value (NULL)
static bool is_compressed ()
trait if sparse vector is "compressed" (false)
Access to internals
void sync (bool)
syncronize internal structures
size_type extract (value_type *arr, size_type size, size_type offset=0, bool zero_mem=true, allocator_pool_type *pool_ptr=0) const
Bulk export list of elements to a C-style array.
size_type extract_range (value_type *arr, size_type size, size_type offset, bool zero_mem=true) const
extract small window without use of masking vector
size_type extract_plains (value_type *arr, size_type size, size_type offset, bool zero_mem=true) const
extract medium window without use of masking vector
size_type effective_size () const
size of sparse vector (may be different for RSC)
size_type effective_vector_max () const
Always 1 (non-matrix type)
static size_type translate_address (size_type i)
address translation for this type of container
static void throw_range_error (const char *err_msg)
throw range error
static void throw_bad_alloc ()
throw bad alloc
static bool find_rank (bm::id_t rank, bm::id_t &pos)
find position of compressed element by its rank
Additional Inherited Members
Static Public Member Functions inherited from bm::base_sparse_vector< Val, BV, 1 >
static unsigned plains ()
get total number of bit-plains in the vector
static unsigned stored_plains ()
Number of stored bit-plains (value plains + extra.
Static Protected Member Functions inherited from bm::base_sparse_vector< Val, BV, 1 >
static unsigned value_bits ()
Number of total bit-plains in the value type.
static unsigned null_plain ()
plain index for the "NOT NULL" flag1s plain
Protected Attributes inherited from bm::base_sparse_vector< Val, BV, 1 >
bmatrix_type bmatr_
bit-transposed matrix
size_type size_
array size
unsigned effective_plains_
Detailed Description
template<class Val, class BV>
class bm::sparse_vector< Val, BV >
sparse vector with runtime compression using bit transposition method
Sparse vector implements variable bit-depth storage model. Initial data is bit-transposed into bit-planes so each element may use less memory than the original native data type prescribes. For example, 32-bit integer may only use 20 bits.
Another level of compression is provided by bit-vector (BV template parameter) used for storing bit planes. bvector<> implements varians of on the fly block compression, so if a significant area of a sparse vector uses less bits - it will save memory.
Overall it provides variable bit-depth compression, sparse compression in bit-plains.
Examples:
rscsample01.cpp, svsample01.cpp, svsample02.cpp, svsample03.cpp, svsample04.cpp, svsample05.cpp, svsample06.cpp, xsample01.cpp, xsample02.cpp, and xsample03.cpp.
Definition at line 75 of file bmsparsevec.h.
Member Typedef Documentation
allocation_policy_type
template<class Val, class BV> typedef bvector_type::allocation_policy bm::sparse_vector< Val, BV >::allocation_policy_type
Definition at line 85 of file bmsparsevec.h.
allocator_pool_type
template<class Val, class BV> typedef allocator_type::allocator_pool_type bm::sparse_vector< Val, BV >::allocator_pool_type
Definition at line 87 of file bmsparsevec.h.
allocator_type
template<class Val, class BV> typedef BV::allocator_type bm::sparse_vector< Val, BV >::allocator_type
Definition at line 84 of file bmsparsevec.h.
bmatrix_type
template<class Val, class BV> typedef bm::basic_bmatrix<BV> bm::sparse_vector< Val, BV >::bmatrix_type
Definition at line 88 of file bmsparsevec.h.
bvector_enumerator_type
template<class Val, class BV> typedef bvector_type::enumerator bm::sparse_vector< Val, BV >::bvector_enumerator_type
Definition at line 86 of file bmsparsevec.h.
bvector_type
template<class Val, class BV> typedef BV bm::sparse_vector< Val, BV >::bvector_type
Definition at line 80 of file bmsparsevec.h.
bvector_type_const_ptr
template<class Val, class BV> typedef const bvector_type* bm::sparse_vector< Val, BV >::bvector_type_const_ptr
Definition at line 82 of file bmsparsevec.h.
bvector_type_ptr
template<class Val, class BV> typedef bvector_type* bm::sparse_vector< Val, BV >::bvector_type_ptr
Definition at line 81 of file bmsparsevec.h.
const_reference
template<class Val, class BV> typedef const value_type& bm::sparse_vector< Val, BV >::const_reference
Definition at line 83 of file bmsparsevec.h.
parent_type
template<class Val, class BV> typedef base_sparse_vector<Val, BV, 1> bm::sparse_vector< Val, BV >::parent_type
Definition at line 89 of file bmsparsevec.h.
size_type
template<class Val, class BV> typedef bm::id_t bm::sparse_vector< Val, BV >::size_type
Definition at line 79 of file bmsparsevec.h.
value_type
template<class Val, class BV> typedef Val bm::sparse_vector< Val, BV >::value_type
Definition at line 78 of file bmsparsevec.h.
Member Enumeration Documentation
octet_plains
template<class Val, class BV> enum bm::sparse_vector::octet_plains protected
Enumerator
sv_octet_plains
Definition at line 797 of file bmsparsevec.h.
Constructor & Destructor Documentation
sparse_vector() [1/3]
template<class Val , class BV > bm::sparse_vector< Val, BV >::sparse_vector (bm::null_support null_able = bm::no_null, allocation_policy_type ap = allocation_policy_type(), size_type bv_max_size = bm::id_max, const allocator_type & alloc = allocator_type())
Sparse vector constructor.
Parameters
null_able - defines if vector supports NULL values flag by default it is OFF, use bm::use_null to enable it
ap - allocation strategy for underlying bit-vectors Default allocation policy uses BM_BIT setting (fastest access)
bv_max_size - maximum possible size of underlying bit-vectors Please note, this is NOT size of svector itself, it is dynamic upper limit which should be used very carefully if we surely know the ultimate size
alloc - allocator for bit-vectors
See also
bvector<>
bm::bvector<>::allocation_policy
bm::startegy
Definition at line 836 of file bmsparsevec.h.
Referenced by bm::sparse_vector< unsigned, bm::bvector<> >::operator=().
sparse_vector() [2/3]
template<class Val, class BV> bm::sparse_vector< Val, BV >::sparse_vector (const sparse_vector< Val, BV > & sv)
copy-ctor
Definition at line 847 of file bmsparsevec.h.
sparse_vector() [3/3]
template<class Val, class BV> bm::sparse_vector< Val, BV >::sparse_vector (sparse_vector< Val, BV > && sv)
move-ctor
Definition at line 855 of file bmsparsevec.h.
~sparse_vector()
template<class Val , class BV > bm::sparse_vector< Val, BV >::~sparse_vector ()
Definition at line 866 of file bmsparsevec.h.
Referenced by bm::sparse_vector< unsigned, bm::bvector<> >::operator=().
Member Function Documentation
at()
template<class Val, class BV> sparse_vector< Val, BV >::value_type bm::sparse_vector< Val, BV >::at (size_type idx) const
access specified element with bounds checking
Parameters
idx - element index
Returns
value of the element
Definition at line 1373 of file bmsparsevec.h.
Referenced by main(), bm::sparse_vector< unsigned, bm::bvector<> >::operator[](), and print_svector().
begin()
template<class Val , class BV > sparse_vector< Val, BV >::const_iterator bm::sparse_vector< Val, BV >::begin () const
Provide const iterator access to container content.
Definition at line 1768 of file bmsparsevec.h.
Referenced by build_vector_pairs(), main(), and bm::sparse_vector< unsigned, bm::bvector<> >::operator[]().
calc_stat()
template<class Val, class BV> void bm::sparse_vector< Val, BV >::calc_stat (struct sparse_vector< Val, BV >::statistics * st) const
Calculates memory statistics.
Function fills statistics structure containing information about how this vector uses memory and estimation of max. amount of memory bvector needs to serialize itself.
Parameters
st - pointer on statistics structure to be filled in.
See also
statistics
Definition at line 1564 of file bmsparsevec.h.
Referenced by bm::sparse_vector< unsigned, bm::bvector<> >::resize().
clear() [1/2]
template<class Val , class BV > void bm::sparse_vector< Val, BV >::clear (size_type idx, bool set_null = false)
clear specified element with bounds checking and automatic resize
Parameters
idx - element index
set_null - if true the value receives NULL (unassigned) value
Definition at line 1418 of file bmsparsevec.h.
Referenced by main().
clear() [2/2]
template<class Val , class BV > void bm::sparse_vector< Val, BV >::clear ()
resize to zero, free memory
Definition at line 1533 of file bmsparsevec.h.
Referenced by bm::sparse_vector< unsigned, bm::bvector<> >::is_compressed(), bm::sparse_vector< unsigned, bm::bvector<> >::operator=(), and bm::sparse_vector< unsigned, bm::bvector<> >::operator[]().
clear_range()
template<class Val, class BV> sparse_vector< Val, BV > & bm::sparse_vector< Val, BV >::clear_range (size_type left, size_type right, bool set_null = false)
clear range (assign bit 0 for all plains)
Parameters
left - interval start
right - interval end (closed interval)
set_null - set cleared values to unassigned (NULL)
Definition at line 1552 of file bmsparsevec.h.
Referenced by bm::sparse_vector< unsigned, bm::bvector<> >::is_compressed().
copy_range()
template<class Val, class BV> void bm::sparse_vector< Val, BV >::copy_range (const sparse_vector< Val, BV > & sv, size_type left, size_type right)
copy range of values from another sparse vector
Copy [left..right] values from the source vector, clear everything outside the range.
Parameters
sv - source vector
left - index from in losed diapason of [left..right]
right - index to in losed diapason of [left..right]
Definition at line 1698 of file bmsparsevec.h.
Referenced by bm::sparse_vector< unsigned, bm::bvector<> >::resize().
decode()
template<class Val , class BV > sparse_vector< Val, BV >::size_type bm::sparse_vector< Val, BV >::decode (value_type * arr, size_type idx_from, size_type dec_size, bool zero_mem = true) const
Bulk export list of elements to a C-style array.
For efficiency, this is left as a low level function, it does not do any bounds checking on the target array, it will override memory and crash if you are not careful with allocation and request size.
Parameters
arr - dest array
idx_from - index in the sparse vector to export from
dec_size - decoding size (array allocation should match)
zero_mem - set to false if target array is pre-initialized with 0s to avoid performance penalty
Returns
number of actually exported elements (can be less than requested)
See also
gather
Definition at line 994 of file bmsparsevec.h.
Referenced by bm::sparse_vector< unsigned, bm::bvector<> >::is_compressed(), and main().
effective_size()
template<class Val, class BV> size_type bm::sparse_vector< Val, BV >::effective_size () const inline
size of sparse vector (may be different for RSC)
Definition at line 782 of file bmsparsevec.h.
effective_vector_max()
template<class Val, class BV> size_type bm::sparse_vector< Val, BV >::effective_vector_max () const inline
Always 1 (non-matrix type)
Definition at line 787 of file bmsparsevec.h.
empty()
template<class Val, class BV> bool bm::sparse_vector< Val, BV >::empty () const inline
return true if vector is empty
Returns
true if empty
Definition at line 593 of file bmsparsevec.h.
Referenced by bm::sparse_vector< Val, BV >::const_iterator::const_iterator(), main(), bm::sparse_vector< Val, BV >::back_insert_iterator::operator++(), and run_benchmark().
end()
template<class Val, class BV> const_iterator bm::sparse_vector< Val, BV >::end () const inline
Provide const iterator access to the end.
Definition at line 447 of file bmsparsevec.h.
Referenced by build_vector_pairs(), and main().
equal()
template<class Val, class BV> bool bm::sparse_vector< Val, BV >::equal (const sparse_vector< Val, BV > & sv, bm::null_support null_able = bm::use_null) const
check if another sparse vector has the same content and size
Parameters
sv - sparse vector for comparison
null_able - flag to consider NULL vector in comparison (default) or compare only value content plains
Returns
true, if it is the same
Definition at line 1758 of file bmsparsevec.h.
Referenced by main(), and bm::sparse_vector< unsigned, bm::bvector<> >::resize().
extract()
template<class Val , class BV > sparse_vector< Val, BV >::size_type bm::sparse_vector< Val, BV >::extract (value_type * arr, size_type size, size_type offset = 0, bool zero_mem = true, allocator_pool_type * pool_ptr = 0) const
Bulk export list of elements to a C-style array.
Use of all extract() methods is restricted. Please consider decode() for the same purpose.
Parameters
arr - dest array
size - dest size
offset - target index in the sparse vector to export from
zero_mem - set to false if target array is pre-initialized with 0s to avoid performance penalty
Returns
number of exported elements
See also
decode
Decoder functor
Definition at line 1280 of file bmsparsevec.h.
Referenced by bm::sparse_vector< unsigned, bm::bvector<> >::sync(), and bm::sparse_vector< Val, BV >::const_iterator::value().
extract_plains()
template<class Val , class BV > sparse_vector< Val, BV >::size_type bm::sparse_vector< Val, BV >::extract_plains (value_type * arr, size_type size, size_type offset, bool zero_mem = true) const
extract medium window without use of masking vector
See also
decode
Definition at line 1235 of file bmsparsevec.h.
Referenced by bm::sparse_vector< unsigned, bm::bvector<> >::sync().
extract_range()
template<class Val , class BV > sparse_vector< Val, BV >::size_type bm::sparse_vector< Val, BV >::extract_range (value_type * arr, size_type size, size_type offset, bool zero_mem = true) const
extract small window without use of masking vector
See also
decode
Definition at line 1155 of file bmsparsevec.h.
Referenced by bm::sparse_vector< unsigned, bm::bvector<> >::sync().
filter()
template<class Val, class BV> void bm::sparse_vector< Val, BV >::filter (const bvector_type & bv_mask)
Apply value filter, defined by mask vector.
All bit-plains are ANDed against the filter mask.
Definition at line 1733 of file bmsparsevec.h.
Referenced by bm::sparse_vector< unsigned, bm::bvector<> >::resize().
find_rank()
template<class Val , class BV > bool bm::sparse_vector< Val, BV >::find_rank (bm::id_t rank, bm::id_t & pos) static
find position of compressed element by its rank
Definition at line 1541 of file bmsparsevec.h.
Referenced by bm::sparse_vector< unsigned, bm::bvector<> >::translate_address().
gather()
template<class Val , class BV > sparse_vector< Val, BV >::size_type bm::sparse_vector< Val, BV >::gather (value_type * arr, const size_type * idx, size_type size, bm::sort_order sorted_idx) const
Gather elements to a C-style array.
Gather collects values from different locations, for best performance feed it with sorted list of indexes.
Faster than one-by-one random access.
For efficiency, this is left as a low level function, it does not do any bounds checking on the target array, it will override memory and crash if you are not careful with allocation and request size.
Parameters
arr - dest array
idx - index list to gather elements
size - decoding index list size (array allocation should match)
sorted_idx - sort order directive for the idx array (BM_UNSORTED, BM_SORTED, BM_UNKNOWN) Sort order affects both performance and correctness(!), use BM_UNKNOWN if not sure.
Returns
number of actually exported elements (can be less than requested)
See also
decode
Definition at line 1014 of file bmsparsevec.h.
Referenced by bm::sparse_vector< unsigned, bm::bvector<> >::is_compressed().
get()
template<class Val , class BV > sparse_vector< Val, BV >::value_type bm::sparse_vector< Val, BV >::get (bm::id_t idx) const
get specified element without bounds checking
Parameters
idx - element index
Returns
value of the element
Definition at line 1384 of file bmsparsevec.h.
Referenced by counting_sort_naive(), and print_sorted().
get_back_inserter()
template<class Val, class BV> back_insert_iterator bm::sparse_vector< Val, BV >::get_back_inserter () inline
Provide back insert iterator Back insert iterator implements buffered insertion, which is faster, than random access or push_back.
Definition at line 458 of file bmsparsevec.h.
Referenced by generate_test_set().
get_const_iterator()
template<class Val, class BV> const_iterator bm::sparse_vector< Val, BV >::get_const_iterator (size_type idx) const inline
Get const_itertor re-positioned to specific element.
Parameters
idx - position in the sparse vector
Definition at line 452 of file bmsparsevec.h.
get_remap_buffer()
template<class Val, class BV> const unsigned char* bm::sparse_vector< Val, BV >::get_remap_buffer () const inline protected
Definition at line 818 of file bmsparsevec.h.
import()
template<class Val , class BV > void bm::sparse_vector< Val, BV >::import (const value_type * arr, size_type arr_size, size_type offset = 0)
Import list of elements from a C-style array.
Parameters
arr - source array
arr_size - source size
offset - target index in the sparse vector
Definition at line 908 of file bmsparsevec.h.
Referenced by convert_bv2sv(), and main().
import_back()
template<class Val , class BV > void bm::sparse_vector< Val, BV >::import_back (const value_type * arr, size_type arr_size)
Import list of elements from a C-style array (pushed back)
Parameters
arr - source array
srr_size - source size
Definition at line 984 of file bmsparsevec.h.
Referenced by bm::sparse_vector< unsigned, bm::bvector<> >::is_compressed().
inc()
template<class Val , class BV > void bm::sparse_vector< Val, BV >::inc (size_type idx)
increment specified element by one
Parameters
idx - element index
Definition at line 1513 of file bmsparsevec.h.
Referenced by counting_sort(), counting_sort_parallel(), counting_sort_subbatch(), and bm::sparse_vector< unsigned, bm::bvector<> >::operator[]().
init_remap_buffer()
template<class Val, class BV> unsigned char* bm::sparse_vector< Val, BV >::init_remap_buffer () inline protected
Definition at line 819 of file bmsparsevec.h.
is_compressed()
template<class Val, class BV> static bool bm::sparse_vector< Val, BV >::is_compressed () inline static
trait if sparse vector is "compressed" (false)
Definition at line 474 of file bmsparsevec.h.
is_remap()
template<class Val, class BV> bool bm::sparse_vector< Val, BV >::is_remap () const inline protected
Definition at line 816 of file bmsparsevec.h.
join()
template<class Val, class BV> sparse_vector< Val, BV > & bm::sparse_vector< Val, BV >::join (const sparse_vector< Val, BV > & sv)
join all with another sparse vector using OR operation
Parameters
sv - argument vector to join with
Returns
slf reference
See also
merge
Definition at line 1621 of file bmsparsevec.h.
Referenced by main(), and bm::sparse_vector< unsigned, bm::bvector<> >::resize().
merge()
template<class Val, class BV> sparse_vector< Val, BV > & bm::sparse_vector< Val, BV >::merge (sparse_vector< Val, BV > & sv)
merge with another sparse vector using OR operation Merge is different from join(), because it borrows data from the source vector, so it gets modified.
Parameters
sv - [in, out]argument vector to join with (vector mutates)
Returns
slf reference
See also
join
Definition at line 1660 of file bmsparsevec.h.
Referenced by counting_sort_parallel(), and bm::sparse_vector< unsigned, bm::bvector<> >::resize().
operator=() [1/2]
template<class Val, class BV> sparse_vector<Val,BV>& bm::sparse_vector< Val, BV >::operator= (const sparse_vector< Val, BV > & sv) inline
copy assignmment operator
Definition at line 356 of file bmsparsevec.h.
operator=() [2/2]
template<class Val, class BV> sparse_vector<Val,BV>& bm::sparse_vector< Val, BV >::operator= (sparse_vector< Val, BV > && sv) inline
move assignmment operator
Definition at line 369 of file bmsparsevec.h.
operator[]() [1/2]
template<class Val, class BV> reference bm::sparse_vector< Val, BV >::operator[] (size_type idx) inline
Operator to get write access to an element.
Definition at line 389 of file bmsparsevec.h.
operator[]() [2/2]
template<class Val, class BV> value_type bm::sparse_vector< Val, BV >::operator[] (size_type idx) const inline
get specified element without bounds checking
Parameters
idx - element index
Returns
value of the element
Definition at line 396 of file bmsparsevec.h.
optimize()
template<class Val, class BV> void bm::sparse_vector< Val, BV >::optimize (bm::word_t * temp_block = 0, typename bvector_type::optmode opt_mode = bvector_type::opt_compress, typename sparse_vector< Val, BV >::statistics * stat = 0)
run memory optimization for all vector plains
Parameters
temp_block - pre-allocated memory block to avoid unnecessary re-allocs
opt_mode - requested compression depth
stat - memory allocation statistics after optimization
Definition at line 1584 of file bmsparsevec.h.
Referenced by convert_bv2sv(), main(), and bm::sparse_vector< unsigned, bm::bvector<> >::resize().
optimize_gap_size()
template<class Val , class BV > void bm::sparse_vector< Val, BV >::optimize_gap_size ()
Optimize sizes of GAP blocks.
This method runs an analysis to find optimal GAP levels for all bit plains of the vector.
Definition at line 1604 of file bmsparsevec.h.
Referenced by bm::sparse_vector< unsigned, bm::bvector<> >::resize().
push_back()
template<class Val , class BV > void bm::sparse_vector< Val, BV >::push_back (value_type v)
push value back into vector
Parameters
v - element value
Definition at line 1435 of file bmsparsevec.h.
Referenced by generate_random_subset(), main(), and bm::sparse_vector< unsigned, bm::bvector<> >::operator[]().
push_back_no_null()
template<class Val , class BV > void bm::sparse_vector< Val, BV >::push_back_no_null (value_type v) protected
push value back into vector without NULL semantics
Definition at line 1444 of file bmsparsevec.h.
remap_size()
template<class Val, class BV> size_t bm::sparse_vector< Val, BV >::remap_size () const inline protected
Definition at line 817 of file bmsparsevec.h.
resize()
template<class Val, class BV> void bm::sparse_vector< Val, BV >::resize (size_type sz) inline
resize vector
Parameters
sz - new size
Definition at line 598 of file bmsparsevec.h.
Referenced by main(), and bm::sparse_vector< unsigned, bm::bvector<> >::resize_internal().
resize_internal()
template<class Val, class BV> void bm::sparse_vector< Val, BV >::resize_internal (size_type sz) inline protected
Definition at line 813 of file bmsparsevec.h.
set()
template<class Val , class BV > void bm::sparse_vector< Val, BV >::set (size_type idx, value_type v)
set specified element with bounds checking and automatic resize
Parameters
idx - element index
v - element value
Definition at line 1406 of file bmsparsevec.h.
Referenced by build_histogram(), convert_bv2sv(), counting_sort_naive(), load_snp_report(), and main().
set_allocator_pool()
template<class Val, class BV> void bm::sparse_vector< Val, BV >::set_allocator_pool (allocator_pool_type * pool_ptr)
Set allocator pool for local (non-threaded) memory cyclic(lots of alloc-free ops) opertations.
Definition at line 1777 of file bmsparsevec.h.
Referenced by bm::sparse_vector< unsigned, bm::bvector<> >::effective_vector_max(), and bm::sparse_vector< unsigned, bm::bvector<> >::set_allocator_pool().
set_null()
template<class Val , class BV > void bm::sparse_vector< Val, BV >::set_null (size_type idx)
set specified element to unassigned value (NULL)
Parameters
idx - element index
Definition at line 900 of file bmsparsevec.h.
Referenced by bm::sparse_vector< unsigned, bm::bvector<> >::get_back_inserter(), main(), and bm::sparse_vector< unsigned, bm::bvector<> >::operator[]().
set_remap()
template<class Val, class BV> void bm::sparse_vector< Val, BV >::set_remap () inline protected
Definition at line 820 of file bmsparsevec.h.
set_value()
template<class Val , class BV > void bm::sparse_vector< Val, BV >::set_value (size_type idx, value_type v) protected
set value without checking boundaries
Definition at line 1453 of file bmsparsevec.h.
set_value_no_null()
template<class Val , class BV > void bm::sparse_vector< Val, BV >::set_value_no_null (size_type idx, value_type v) protected
set value without checking boundaries or support of NULL
Definition at line 1464 of file bmsparsevec.h.
size()
template<class Val, class BV> size_type bm::sparse_vector< Val, BV >::size () const inline
return size of the vector
Returns
size of sparse vector
Definition at line 588 of file bmsparsevec.h.
Referenced by bm::sparse_vector< Val, BV >::const_iterator::advance(), bm::sparse_vector< unsigned, bm::bvector<> >::copy_range(), bm::sparse_vector< unsigned, bm::bvector<> >::effective_size(), bm::sparse_vector< unsigned, bm::bvector<> >::empty(), bm::sparse_vector< Val, BV >::const_iterator::go_to(), bm::sparse_vector< unsigned, bm::bvector<> >::is_compressed(), bm::sparse_vector< unsigned, bm::bvector<> >::join(), main(), bm::sparse_vector< unsigned, bm::bvector<> >::merge(), print_svector(), bm::sparse_vector< unsigned, bm::bvector<> >::size_internal(), and bm::sparse_vector< Val, BV >::const_iterator::skip_zero_values().
size_internal()
template<class Val, class BV> size_type bm::sparse_vector< Val, BV >::size_internal () const inline protected
Definition at line 814 of file bmsparsevec.h.
swap()
template<class Val, class BV> void bm::sparse_vector< Val, BV >::swap (sparse_vector< Val, BV > & sv)
content exchange
Definition at line 872 of file bmsparsevec.h.
Referenced by bm::sparse_vector< unsigned, bm::bvector<> >::is_compressed(), and bm::sparse_vector< unsigned, bm::bvector<> >::operator=().
sync()
template<class Val, class BV> void bm::sparse_vector< Val, BV >::sync (bool) inline
syncronize internal structures
Definition at line 707 of file bmsparsevec.h.
throw_bad_alloc()
template<class Val , class BV > void bm::sparse_vector< Val, BV >::throw_bad_alloc () static
throw bad alloc
Definition at line 892 of file bmsparsevec.h.
Referenced by bm::sparse_vector< unsigned, bm::bvector<> >::translate_address().
throw_range_error()
template<class Val , class BV > void bm::sparse_vector< Val, BV >::throw_range_error (const char * err_msg) static
throw range error
Definition at line 880 of file bmsparsevec.h.
Referenced by bm::sparse_vector< unsigned, bm::bvector<> >::translate_address().
translate_address()
template<class Val, class BV> static size_type bm::sparse_vector< Val, BV >::translate_address (size_type i) inline static
address translation for this type of container
Definition at line 756 of file bmsparsevec.h.
Friends And Related Function Documentation
rsc_sparse_vector
template<class Val, class BV> template<class V , class SV > friend class rsc_sparse_vector friend
Definition at line 823 of file bmsparsevec.h.
sparse_vector_deserializer
template<class Val, class BV> template<class SVect > friend class sparse_vector_deserializer friend
Definition at line 826 of file bmsparsevec.h.
sparse_vector_scanner
template<class Val, class BV> template<class SVect > friend class sparse_vector_scanner friend
Definition at line 824 of file bmsparsevec.h.
sparse_vector_serializer
template<class Val, class BV> template<class SVect > friend class sparse_vector_serializer friend
Definition at line 825 of file bmsparsevec.h.
Field Documentation
back_insert_iterator
template<class Val, class BV> friend bm::sparse_vector< Val, BV >::back_insert_iterator
Definition at line 324 of file bmsparsevec.h.
Referenced by bm::sparse_vector< unsigned, bm::bvector<> >::get_back_inserter().
const_iterator
template<class Val, class BV> friend bm::sparse_vector< Val, BV >::const_iterator
Definition at line 323 of file bmsparsevec.h.
Referenced by bm::sparse_vector< unsigned, bm::bvector<> >::end(), bm::sparse_vector< unsigned, bm::bvector<> >::get_const_iterator(), and bm::sparse_vector< unsigned, bm::bvector<> >::operator[]().
The documentation for this class was generated from the following file:
bmsparsevec.h