BitMagic-C++: bm::bvector_mini< A > Class Template Reference
bm::bvector_mini< A > Class Template Reference
Bitvector class with very limited functionality.
#include <bmvmin.h>
Public Member Functions
bvector_mini (unsigned size)
bvector_mini (const bvector_mini &bvect)
~bvector_mini ()
int is_bit_true (unsigned pos) const
Checks if bit pos 1 or 0. Returns 0 if 0 and non zero otherwise.
void set_bit (unsigned pos)
Sets bit number pos to 1.
void clear_bit (unsigned pos)
Sets bit number pos to 0.
unsigned bit_count () const
Counts number of bits ON.
int compare (const bvector_mini &bvect)
Comparison.
unsigned get_first () const
Returns index of the first ON bit.
unsigned get_next (unsigned idx) const
Returns index of next bit, which is ON.
void combine_and (const bvector_mini &bvect)
void combine_xor (const bvector_mini &bvect)
void combine_or (const bvector_mini &bvect)
void combine_sub (const bvector_mini &bvect)
const unsigned * get_buf () const
unsigned mem_used () const
void swap (bvector_mini &bvm)
Detailed Description
template<class A>
class bm::bvector_mini< A >
Bitvector class with very limited functionality.
Class implements simple bitset and used for internal and testing purposes.
Definition at line 269 of file bmvmin.h.
Constructor & Destructor Documentation
bvector_mini() [1/2]
template<class A > bm::bvector_mini< A >::bvector_mini (unsigned size) inline
Definition at line 272 of file bmvmin.h.
bvector_mini() [2/2]
template<class A > bm::bvector_mini< A >::bvector_mini (const bvector_mini< A > & bvect) inline
Definition at line 280 of file bmvmin.h.
~bvector_mini()
template<class A > bm::bvector_mini< A >::~bvector_mini () inline
Definition at line 288 of file bmvmin.h.
Member Function Documentation
bit_count()
template<class A > unsigned bm::bvector_mini< A >::bit_count () const inline
Counts number of bits ON.
Definition at line 321 of file bmvmin.h.
Referenced by bm::bvector_mini< A >::compare().
clear_bit()
template<class A > void bm::bvector_mini< A >::clear_bit (unsigned pos) inline
Sets bit number pos to 0.
Definition at line 312 of file bmvmin.h.
combine_and()
template<class A > void bm::bvector_mini< A >::combine_and (const bvector_mini< A > & bvect) inline
Definition at line 421 of file bmvmin.h.
References bm::bvector_mini< A >::get_buf().
combine_or()
template<class A > void bm::bvector_mini< A >::combine_or (const bvector_mini< A > & bvect) inline
Definition at line 446 of file bmvmin.h.
References bm::bvector_mini< A >::get_buf().
combine_sub()
template<class A > void bm::bvector_mini< A >::combine_sub (const bvector_mini< A > & bvect) inline
Definition at line 458 of file bmvmin.h.
References bm::bvector_mini< A >::get_buf().
combine_xor()
template<class A > void bm::bvector_mini< A >::combine_xor (const bvector_mini< A > & bvect) inline
Definition at line 433 of file bmvmin.h.
References bm::bvector_mini< A >::get_buf().
compare()
template<class A > int bm::bvector_mini< A >::compare (const bvector_mini< A > & bvect) inline
Comparison.
Definition at line 335 of file bmvmin.h.
References bm::bvector_mini< A >::bit_count(), bm::bvector_mini< A >::get_first(), and bm::bvector_mini< A >::get_next().
get_buf()
template<class A > const unsigned* bm::bvector_mini< A >::get_buf () const inline
Definition at line 470 of file bmvmin.h.
Referenced by bm::bvector_mini< A >::combine_and(), bm::bvector_mini< A >::combine_or(), bm::bvector_mini< A >::combine_sub(), and bm::bvector_mini< A >::combine_xor().
get_first()
template<class A > unsigned bm::bvector_mini< A >::get_first () const inline
Returns index of the first ON bit.
Definition at line 372 of file bmvmin.h.
Referenced by bm::bvector_mini< A >::compare().
get_next()
template<class A > unsigned bm::bvector_mini< A >::get_next (unsigned idx) const inline
Returns index of next bit, which is ON.
Definition at line 396 of file bmvmin.h.
Referenced by bm::bvector_mini< A >::compare().
is_bit_true()
template<class A > int bm::bvector_mini< A >::is_bit_true (unsigned pos) const inline
Checks if bit pos 1 or 0. Returns 0 if 0 and non zero otherwise.
Definition at line 294 of file bmvmin.h.
mem_used()
template<class A > unsigned bm::bvector_mini< A >::mem_used () const inline
Definition at line 471 of file bmvmin.h.
set_bit()
template<class A > void bm::bvector_mini< A >::set_bit (unsigned pos) inline
Sets bit number pos to 1.
Definition at line 303 of file bmvmin.h.
swap()
template<class A > void bm::bvector_mini< A >::swap (bvector_mini< A > & bvm) inline
Definition at line 476 of file bmvmin.h.
The documentation for this class was generated from the following file:
bmvmin.h