BitMagic-C++: bm::bvector< Alloc >::mem_pool_guard Class Reference
bm::bvector< Alloc >::mem_pool_guard Class Reference
BitMagic Library » bvector<> container
#include <bm.h>
Public Member Functions
mem_pool_guard ()
mem_pool_guard (allocator_pool_type &pool, bvector< Alloc > &bv)
~mem_pool_guard ()
void assign_if_not_set (allocator_pool_type &pool, bvector< Alloc > &bv)
Detailed Description
template<class Alloc>
class bm::bvector< Alloc >::mem_pool_guard
Resource guard for bvector<>::set_allocator_pool()
Definition at line 1196 of file bm.h.
Constructor & Destructor Documentation
mem_pool_guard() [1/2]
template<class Alloc> bm::bvector< Alloc >::mem_pool_guard::mem_pool_guard () inline
Definition at line 1199 of file bm.h.
mem_pool_guard() [2/2]
template<class Alloc> bm::bvector< Alloc >::mem_pool_guard::mem_pool_guard (allocator_pool_type & pool, bvector< Alloc > & bv) inline
Definition at line 1202 of file bm.h.
References bm::bvector< Alloc >::set_allocator_pool().
~mem_pool_guard()
template<class Alloc> bm::bvector< Alloc >::mem_pool_guard::~mem_pool_guard () inline
Definition at line 1207 of file bm.h.
Member Function Documentation
assign_if_not_set()
template<class Alloc> void bm::bvector< Alloc >::mem_pool_guard::assign_if_not_set (allocator_pool_type & pool, bvector< Alloc > & bv) inline
Definition at line 1213 of file bm.h.
References BM_ASSERT, bm::bvector< Alloc >::get_allocator_pool(), and bm::bvector< Alloc >::set_allocator_pool().
Referenced by bm::set2set_11_transform< SV >::attach_sv(), bm::sparse_vector_scanner< SV >::find_eq(), and bm::set2set_11_transform< SV >::remap().
The documentation for this class was generated from the following file:
bm.h