BitMagic-C++: bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE > Class Template Reference
bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE > Class Template Reference
BitMagic Library » sparse_vector<>
sparse vector for strings with compression using bit transposition method
#include <bmstrsparsevec.h>
Data Structures
class back_insert_iterator
Back insert iterator implements buffered insert, faster than generic access assignment.
class const_iterator
Const iterator to do quick traverse of the sparse vector.
class const_reference
Reference class to access elements via common [] operator.
struct is_remap_support
struct is_rsc_support
class reference
Reference class to access elements via common [] operator.
struct statistics
Public Types
enum octet_plains { sv_octet_plains = MAX_STR_SIZE }
typedef CharType value_type
typedef bm::id_t size_type
typedef BV bvector_type
typedef bvector_type * bvector_type_ptr
typedef const bvector_type * bvector_type_const_ptr
typedef BV::allocator_type allocator_type
typedef bvector_type::allocation_policy allocation_policy_type
typedef bvector_type::enumerator bvector_enumerator_type
typedef allocator_type::allocator_pool_type allocator_pool_type
typedef bm::basic_bmatrix< BV > bmatrix_type
typedef base_sparse_vector< CharType, BV, MAX_STR_SIZE > parent_type
typedef bm::heap_matrix< unsigned char, MAX_STR_SIZE, 256, typename bvector_type::allocator_type > plain_octet_matrix_type
Public Types inherited from bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >
enum bit_plains
enum vector_capacity
typedef CharType value_type
typedef bm::id_t size_type
typedef BV bvector_type
typedef bvector_type * bvector_type_ptr
typedef const bvector_type * bvector_type_const_ptr
typedef const value_type & const_reference
typedef BV::allocator_type allocator_type
typedef bvector_type::allocation_policy allocation_policy_type
typedef bvector_type::enumerator bvector_enumerator_type
typedef allocator_type::allocator_pool_type allocator_pool_type
typedef bm::basic_bmatrix< BV > bmatrix_type
Public Member Functions
str_sparse_vector (bm::null_support null_able=bm::no_null, allocation_policy_type ap=allocation_policy_type(), size_type bv_max_size=bm::id_max, const allocator_type &alloc=allocator_type())
Sparse vector constructor.
str_sparse_vector (const str_sparse_vector &str_sv)
str_sparse_vector< CharType, BV, MAX_STR_SIZE > & operator= (const str_sparse_vector< CharType, BV, MAX_STR_SIZE > &str_sv)
str_sparse_vector (str_sparse_vector< CharType, BV, MAX_STR_SIZE > &&str_sv) BMNOEXEPT
str_sparse_vector< CharType, BV, MAX_STR_SIZE > & operator= (str_sparse_vector< CharType, BV, MAX_STR_SIZE > &&str_sv) BMNOEXEPT
void sync (bool force)
syncronize internal structures
bool equal (const str_sparse_vector< CharType, BV, MAX_STR_SIZE > &sv, bm::null_support null_able=bm::use_null) const
check if another sparse vector has the same content and size
size_type effective_size () const
size of sparse vector (may be different for RSC)
String element access
reference operator[] (size_type idx)
Operator to get write access to an element.
const_reference operator[] (size_type idx) const
Operator to get read access to an element.
void set (size_type idx, const value_type *str)
set specified element with bounds checking and automatic resize
void insert (size_type idx, const value_type *str)
insert the specified element
size_type get (size_type idx, value_type *str, size_type buf_size) const
get specified element
template<typename StrType >
void assign (size_type idx, const StrType &str)
set specified element with bounds checking and automatic resize
template<typename StrType >
void push_back (const StrType &str)
push back a string
void push_back (const value_type *str)
push back a string (zero terminated)
template<typename StrType >
void get (size_type idx, StrType &str) const
get specified string element
void swap (str_sparse_vector &str_sv) BMNOEXEPT
Element comparison functions
int compare (size_type idx, const value_type *str) const
Compare vector element with argument lexicographically.
unsigned common_prefix_length (size_type idx1, size_type idx2) const
Find size of common prefix between two vector elements in octets.
Clear
void clear () BMNOEXEPT
resize to zero, free memory
str_sparse_vector< CharType, BV, MAX_STR_SIZE > & clear_range (size_type left, size_type right, bool set_null=false)
clear range (assign bit 0 for all plains)
Memory optimization/compression
void optimize (bm::word_t *temp_block=0, typename bvector_type::optmode opt_mode=bvector_type::opt_compress, typename str_sparse_vector< CharType, BV, MAX_STR_SIZE >::statistics *stat=0)
run memory optimization for all vector plains
void calc_stat (struct str_sparse_vector< CharType, BV, MAX_STR_SIZE >::statistics *st) const
Calculates memory statistics.
Iterator access
const_iterator begin () const
Provide const iterator access to container content.
const_iterator end () const
Provide const iterator access to the end.
const_iterator get_const_iterator (size_type idx) const
Get const_itertor re-positioned to specific element.
back_insert_iterator get_back_inserter ()
Provide back insert iterator Back insert iterator implements buffered insertion, which is faster, than random access or push_back.
Export content to C-style
template<typename CharMatrix >
size_type decode (CharMatrix &cmatr, size_type idx_from, size_type dec_size, bool zero_mem=true) const
Bulk export strings to a C-style matrix of chars.
template<typename CharMatrix >
void import (CharMatrix &cmatr, size_type idx_from, size_type imp_size)
Bulk import of strings from a C-style matrix of chars.
template<typename CharMatrix >
void import_back (CharMatrix &cmatr, size_type imp_size)
Bulk push-back import of strings from a C-style matrix of chars.
Public Member Functions inherited from bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >
base_sparse_vector ()
base_sparse_vector (bm::null_support null_able, allocation_policy_type ap, size_type bv_max_size, const allocator_type &alloc)
base_sparse_vector (const base_sparse_vector< CharType, BV, MAX_SIZE > &bsv)
base_sparse_vector (base_sparse_vector< CharType, BV, MAX_SIZE > &&bsv) BMNOEXEPT
void swap (base_sparse_vector< CharType, BV, MAX_SIZE > &bsv) BMNOEXEPT
size_type size () const
void resize (size_type new_size)
void clear_range (size_type left, size_type right, bool set_null)
void clear () BMNOEXEPT
resize to zero, free memory
bool empty () const
void optimize (bm::word_t *temp_block=0, typename bvector_type::optmode opt_mode=bvector_type::opt_compress, typename bvector_type::statistics *stat=0)
run memory optimization for all bit-vector rows
void calc_stat (typename bvector_type::statistics *st) const
Calculates memory statistics.
bool equal (const base_sparse_vector< CharType, BV, MAX_SIZE > &sv, bm::null_support null_able=bm::use_null) const
check if another sparse vector has the same content and size
bool is_nullable () const
check if container supports NULL(unassigned) values
const bvector_type * get_null_bvector () const
Get bit-vector of assigned values or NULL (if not constructed that way)
bool is_null (size_type idx) const
test if specified element is NULL
bvector_type_ptr get_plain (unsigned i)
get access to bit-plain, function checks and creates a plain
bvector_type_const_ptr get_plain (unsigned i) const
get read-only access to bit-plain
unsigned effective_plains () const
Number of effective bit-plains in the value type.
bvector_type_ptr plain (unsigned i)
get access to bit-plain as is (can return NULL)
const bvector_type_ptr plain (unsigned i) const
bvector_type * get_null_bvect ()
void free_plain (unsigned i)
free memory in bit-plain
bm::id64_t get_plains_mask (unsigned element_idx) const
Static Public Member Functions
static bool find_rank (bm::id_t rank, bm::id_t &pos)
find position of compressed element by its rank
Various traits
static bool is_compressed ()
trait if sparse vector is "compressed" (false)
Static Public Member Functions inherited from bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >
static unsigned plains ()
get total number of bit-plains in the vector
static unsigned stored_plains ()
Number of stored bit-plains (value plains + extra.
Protected Member Functions
template<typename CharMatrix >
void import_no_check (CharMatrix &cmatr, size_type idx_from, size_type imp_size)
void set_value (size_type idx, const value_type *str)
set value without checking boundaries
void set_value_no_null (size_type idx, const value_type *str)
set value without checking boundaries or support of NULL
void insert_value (size_type idx, const value_type *str)
insert value without checking boundaries
void insert_value_no_null (size_type idx, const value_type *str)
insert value without checking boundaries or support of NULL
size_type size_internal () const
void resize_internal (size_type sz)
size_t remap_size () const
const unsigned char * get_remap_buffer () const
unsigned char * init_remap_buffer ()
void set_remap ()
Protected Member Functions inherited from bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >
void copy_from (const base_sparse_vector< CharType, BV, MAX_SIZE > &bsv)
void clear_value_plains_from (unsigned plain_idx, size_type idx)
void insert_clear_value_plains_from (unsigned plain_idx, size_type idx)
Static Protected Member Functions
Errors and exceptions
static void throw_range_error (const char *err_msg)
throw range error
static void throw_bad_value (const char *err_msg)
throw domain error
Static Protected Member Functions inherited from bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >
static unsigned value_bits ()
Number of total bit-plains in the value type.
static unsigned null_plain ()
plain index for the "NOT NULL" flag1s plain
Protected Attributes
unsigned remap_flags_
remapping status
plain_octet_matrix_type remap_matrix1_
octet remap table 1
plain_octet_matrix_type remap_matrix2_
octet remap table 2
Protected Attributes inherited from bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >
bmatrix_type bmatr_
bit-transposed matrix
size_type size_
array size
unsigned effective_plains_
Friends
template<class SVect >
class sparse_vector_serializer
template<class SVect >
class sparse_vector_deserializer
Size, etc
size_type size () const
return size of the vector
bool empty () const
return true if vector is empty
void resize (size_type sz)
resize vector
size_type effective_max_str () const
get effective string length used in vector
size_type effective_vector_max () const
get effective string length used in vector
static size_type max_str ()
get maximum string length capacity
remapping, succinct utilities
Remapping implements reduction of dit-depth thus improves search performance. Remapping limits farther modifications of sparse vector.
bool is_remap () const
Get remapping status (true|false)
void remap_from (const str_sparse_vector &str_sv)
Build remapping profile and load content from another sparse vector.
void calc_octet_stat (plain_octet_matrix_type &octet_matrix) const
bool remap_tosv (value_type *sv_str, size_type buf_size, const value_type *str) const
void recalc_remap_matrix2 ()
static void build_octet_remap (plain_octet_matrix_type &octet_remap_matrix1, plain_octet_matrix_type &octet_remap_matrix2, const plain_octet_matrix_type &octet_occupancy_matrix)
static bool remap_tosv (value_type *sv_str, size_type buf_size, const value_type *str, const plain_octet_matrix_type &octet_remap_matrix2)
static bool remap_fromsv (value_type *str, size_type buf_size, const value_type *sv_str, const plain_octet_matrix_type &octet_remap_matrix1)
Detailed Description
template<typename CharType, typename BV, unsigned MAX_STR_SIZE>
class bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >
sparse vector for strings with compression using bit transposition method
Initial string is bit-transposed into bit-planes so collection may use less memory due to prefix sum (GAP) compression in bit-plains.
Examples:
xsample05.cpp.
Definition at line 51 of file bmstrsparsevec.h.
Member Typedef Documentation
allocation_policy_type
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> typedef bvector_type::allocation_policy bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::allocation_policy_type
Definition at line 60 of file bmstrsparsevec.h.
allocator_pool_type
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> typedef allocator_type::allocator_pool_type bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::allocator_pool_type
Definition at line 62 of file bmstrsparsevec.h.
allocator_type
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> typedef BV::allocator_type bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::allocator_type
Definition at line 59 of file bmstrsparsevec.h.
bmatrix_type
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> typedef bm::basic_bmatrix<BV> bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::bmatrix_type
Definition at line 63 of file bmstrsparsevec.h.
bvector_enumerator_type
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> typedef bvector_type::enumerator bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::bvector_enumerator_type
Definition at line 61 of file bmstrsparsevec.h.
bvector_type
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> typedef BV bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::bvector_type
Definition at line 56 of file bmstrsparsevec.h.
bvector_type_const_ptr
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> typedef const bvector_type* bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::bvector_type_const_ptr
Definition at line 58 of file bmstrsparsevec.h.
bvector_type_ptr
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> typedef bvector_type* bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::bvector_type_ptr
Definition at line 57 of file bmstrsparsevec.h.
parent_type
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> typedef base_sparse_vector<CharType, BV, MAX_STR_SIZE> bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::parent_type
Definition at line 64 of file bmstrsparsevec.h.
plain_octet_matrix_type
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> typedef bm::heap_matrix<unsigned char, MAX_STR_SIZE, 256, typename bvector_type::allocator_type> bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::plain_octet_matrix_type
Definition at line 80 of file bmstrsparsevec.h.
size_type
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> typedef bm::id_t bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::size_type
Definition at line 55 of file bmstrsparsevec.h.
value_type
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> typedef CharType bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::value_type
Definition at line 54 of file bmstrsparsevec.h.
Member Enumeration Documentation
octet_plains
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> enum bm::str_sparse_vector::octet_plains
Enumerator
sv_octet_plains
Definition at line 70 of file bmstrsparsevec.h.
Constructor & Destructor Documentation
str_sparse_vector() [1/3]
template<class CharType , class BV , unsigned MAX_STR_SIZE> bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::str_sparse_vector (bm::null_support null_able = bm::no_null, allocation_policy_type ap = allocation_policy_type(), size_type bv_max_size = bm::id_max, const allocator_type & alloc = allocator_type())
Sparse vector constructor.
Parameters
null_able - defines if vector supports NULL values flag by default it is OFF, use bm::use_null to enable it
ap - allocation strategy for underlying bit-vectors Default allocation policy uses BM_BIT setting (fastest access)
bv_max_size - maximum possible size of underlying bit-vectors Please note, this is NOT size of svector itself, it is dynamic upper limit which should be used very carefully if we surely know the ultimate size
alloc - allocator for bit-vectors
See also
bvector<>
bm::bvector<>::allocation_policy
bm::startegy
Definition at line 1048 of file bmstrsparsevec.h.
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::back_insert_iterator::operator++().
str_sparse_vector() [2/3]
template<class CharType , class BV , unsigned MAX_STR_SIZE> bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::str_sparse_vector (const str_sparse_vector< CharType, BV, MAX_STR_SIZE > & str_sv)
copy-ctor
Definition at line 1061 of file bmstrsparsevec.h.
str_sparse_vector() [3/3]
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::str_sparse_vector (str_sparse_vector< CharType, BV, MAX_STR_SIZE > && str_sv) inline
move-ctor
Definition at line 388 of file bmstrsparsevec.h.
References bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_flags_, bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_matrix1_, bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_matrix2_, and bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::swap().
Member Function Documentation
assign()
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> template<typename StrType > void bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::assign (size_type idx, const StrType & str) inline
set specified element with bounds checking and automatic resize
This is an equivalent of set() method, but templetized to be more compatible with the STL std::string and the likes
Parameters
idx - element index (vector auto-resized if needs to)
str - input string expected an STL class with size() support, like basic_string<> or vector<char>
Definition at line 458 of file bmstrsparsevec.h.
References BM_ASSERT, bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::bmatr_, bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::clear_value_plains_from(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_flags_, bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_matrix2_, bm::basic_bmatrix< BV >::set_octet(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::size(), and bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::size_.
Referenced by main(), and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::push_back().
begin()
template<class CharType , class BV , unsigned MAX_STR_SIZE> str_sparse_vector< CharType, BV, MAX_STR_SIZE >::const_iterator bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::begin () const
Provide const iterator access to container content.
Definition at line 1578 of file bmstrsparsevec.h.
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::effective_vector_max(), and main().
build_octet_remap()
template<class CharType , class BV , unsigned MAX_STR_SIZE> void bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::build_octet_remap (plain_octet_matrix_type & octet_remap_matrix1, plain_octet_matrix_type & octet_remap_matrix2, const plain_octet_matrix_type & octet_occupancy_matrix) static
Definition at line 1384 of file bmstrsparsevec.h.
References BM_ASSERT.
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::is_remap(), and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_from().
calc_octet_stat()
template<class CharType , class BV , unsigned MAX_STR_SIZE> void bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::calc_octet_stat (plain_octet_matrix_type & octet_matrix) const
Calculate flags which octets are present on each byte-plain.
Definition at line 1358 of file bmstrsparsevec.h.
References bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::bmatr_, bm::basic_bmatrix< BV >::get_octet(), and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::size().
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::is_remap(), and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_from().
calc_stat()
template<class CharType , class BV , unsigned MAX_STR_SIZE> void bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::calc_stat (struct str_sparse_vector< CharType, BV, MAX_STR_SIZE >::statistics * st) const
Calculates memory statistics.
Function fills statistics structure containing information about how this vector uses memory and estimation of max. amount of memory bvector needs to serialize itself.
Parameters
st - pointer on statistics structure to be filled in.
See also
statistics
Definition at line 1244 of file bmstrsparsevec.h.
References bm::bv_statistics::bit_blocks, BM_ASSERT, bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::calc_stat(), bm::bv_statistics::gap_blocks, bm::bv_statistics::max_serialize_mem, bm::bv_statistics::memory_used, bm::bv_statistics::ptr_sub_blocks, bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_flags_, bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_matrix1_, bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_matrix2_, and bm::bv_statistics::reset().
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::effective_vector_max().
clear()
template<class CharType , class BV , unsigned MAX_STR_SIZE> void bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::clear ()
resize to zero, free memory
Definition at line 1588 of file bmstrsparsevec.h.
References bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::clear().
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::get(), and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_from().
clear_range()
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> str_sparse_vector<CharType, BV, MAX_STR_SIZE>& bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::clear_range (size_type left, size_type right, bool set_null = false) inline
clear range (assign bit 0 for all plains)
Parameters
left - interval start
right - interval end (closed interval)
set_null - set cleared values to unassigned (NULL)
Definition at line 586 of file bmstrsparsevec.h.
References bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::clear_range().
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::import().
common_prefix_length()
template<class CharType , class BV , unsigned MAX_STR_SIZE> unsigned bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::common_prefix_length (size_type idx1, size_type idx2) const
Find size of common prefix between two vector elements in octets.
Returns
size of common prefix
Definition at line 1303 of file bmstrsparsevec.h.
References bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::bmatr_, and bm::basic_bmatrix< BV >::get_octet().
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::get().
compare()
template<class CharType , class BV , unsigned MAX_STR_SIZE> int bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::compare (size_type idx, const value_type * str) const
Compare vector element with argument lexicographically.
NOTE: for a re-mapped container, input string may have no correct remapping, in this case we have an ambiguity (we know it is not equal (0) but LT or GT?). Behavior is undefined.
Parameters
idx - vactor element index
str - argument to compare with
Returns
0 - equal, < 0 - vect[i] < str, >0 otherwise
Definition at line 1274 of file bmstrsparsevec.h.
References BM_ASSERT, bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::bmatr_, bm::basic_bmatrix< BV >::compare_octet(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_flags_, bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_matrix2_, and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::throw_bad_value().
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::get().
decode()
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> template<typename CharMatrix > size_type bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::decode (CharMatrix & cmatr, size_type idx_from, size_type dec_size, bool zero_mem = true) const inline
Bulk export strings to a C-style matrix of chars.
Parameters
cmatr - dest matrix (bm::heap_matrix)
idx_from - index in the sparse vector to export from
dec_size - decoding size (matrix column allocation should match)
zero_mem - set to false if target array is pre-initialized with 0s to avoid performance penalty
Returns
number of actually exported elements (can be less than requested)
Definition at line 789 of file bmstrsparsevec.h.
References BM_ASSERT, bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::bmatr_, bm::basic_bmatrix< BV >::get_row(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_flags_, bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_matrix1_, bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::size(), and bm::bvector< Alloc >::iterator_base::valid().
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_from(), and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::const_iterator::value().
effective_max_str()
template<class CharType , class BV , unsigned MAX_STR_SIZE> str_sparse_vector< CharType, BV, MAX_STR_SIZE >::size_type bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::effective_max_str () const
get effective string length used in vector
Method returns efficiency, how close are we to reserved maximum.
Returns
current string length maximum
Definition at line 1341 of file bmstrsparsevec.h.
References bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::bmatr_, and bm::basic_bmatrix< BV >::row().
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::effective_vector_max(), and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::max_str().
effective_size()
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> size_type bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::effective_size () const inline
size of sparse vector (may be different for RSC)
Definition at line 906 of file bmstrsparsevec.h.
References bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::size().
effective_vector_max()
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> size_type bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::effective_vector_max () const inline
get effective string length used in vector
Returns
current string length maximum
Definition at line 632 of file bmstrsparsevec.h.
References bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::begin(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::calc_stat(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::effective_max_str(), bm::bvector< Alloc >::opt_compress, and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::optimize().
empty()
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> bool bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::empty () const inline
return true if vector is empty
Returns
true if empty
Examples:
xsample05.cpp.
Definition at line 608 of file bmstrsparsevec.h.
References bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::size().
Referenced by main(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::back_insert_iterator::operator++(), and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_from().
end()
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> const_iterator bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::end () const inline
Provide const iterator access to the end.
Definition at line 674 of file bmstrsparsevec.h.
References bm::id_max.
Referenced by main().
equal()
template<class CharType , class BV , unsigned MAX_STR_SIZE> bool bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::equal (const str_sparse_vector< CharType, BV, MAX_STR_SIZE > & sv, bm::null_support null_able = bm::use_null) const
check if another sparse vector has the same content and size
Parameters
sv - sparse vector for comparison
null_able - flag to consider NULL vector in comparison (default) or compare only value content plains
Returns
true, if it is the same
Definition at line 1550 of file bmstrsparsevec.h.
References bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::equal(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_flags_, bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_matrix1_, and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_matrix2_.
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::import_back().
find_rank()
template<class CharType , class BV , unsigned MAX_STR_SIZE> bool bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::find_rank (bm::id_t rank, bm::id_t & pos) static
find position of compressed element by its rank
Definition at line 1329 of file bmstrsparsevec.h.
References BM_ASSERT.
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::import_back().
get() [1/2]
template<class CharType , class BV , unsigned MAX_STR_SIZE> str_sparse_vector< CharType, BV, MAX_STR_SIZE >::size_type bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::get (size_type idx, value_type * str, size_type buf_size) const
get specified element
Parameters
idx - element index
str - string buffer
buf_size - string buffer size
Returns
string length
Examples:
xsample05.cpp.
Definition at line 1196 of file bmstrsparsevec.h.
References bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::bmatr_, bm::basic_bmatrix< BV >::get_octet(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_flags_, and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_matrix1_.
Referenced by check_sparse(), and main().
get() [2/2]
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> template<typename StrType > void bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::get (size_type idx, StrType & str) const inline
get specified string element
Template method expects an STL-compatible type basic_string<>
Parameters
idx - element index (vector auto-resized if needs to)
str - string to get [out]
Definition at line 514 of file bmstrsparsevec.h.
References BM_ASSERT, bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::bmatr_, BMNOEXEPT, bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::clear(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::common_prefix_length(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::compare(), bm::basic_bmatrix< BV >::get_octet(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_flags_, bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_matrix1_, bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::swap(), and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::throw_bad_value().
get_back_inserter()
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> back_insert_iterator bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::get_back_inserter () inline
Provide back insert iterator Back insert iterator implements buffered insertion, which is faster, than random access or push_back.
Definition at line 685 of file bmstrsparsevec.h.
Referenced by main().
get_const_iterator()
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> const_iterator bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::get_const_iterator (size_type idx) const inline
Get const_itertor re-positioned to specific element.
Parameters
idx - position in the sparse vector
Definition at line 679 of file bmstrsparsevec.h.
get_remap_buffer()
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> const unsigned char* bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::get_remap_buffer () const inline protected
Definition at line 1024 of file bmstrsparsevec.h.
References bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_matrix1_.
import()
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> template<typename CharMatrix > void bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::import (CharMatrix & cmatr, size_type idx_from, size_type imp_size) inline
Bulk import of strings from a C-style matrix of chars.
Parameters
cmatr - source matrix (bm::heap_matrix) [in/out] parameter gets modified(corrupted) in the process
idx_from - destination index in the sparse vector
imp_size - import size (number or rows to import)
Definition at line 849 of file bmstrsparsevec.h.
References bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::clear_range(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::import_no_check(), and bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::size_.
import_back()
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> template<typename CharMatrix > void bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::import_back (CharMatrix & cmatr, size_type imp_size) inline
Bulk push-back import of strings from a C-style matrix of chars.
Parameters
cmatr - source matrix (bm::heap_matrix) [in/out] parameter gets modified(corrupted) in the process
imp_size - import size (number or rows to import)
Definition at line 870 of file bmstrsparsevec.h.
References bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::equal(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::find_rank(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::import_no_check(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::size(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::sync(), and bm::use_null.
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::back_insert_iterator::flush().
import_no_check()
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> template<typename CharMatrix > void bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::import_no_check (CharMatrix & cmatr, size_type idx_from, size_type imp_size) inline protected
Definition at line 912 of file bmstrsparsevec.h.
References bm::bit_list(), BM_ASSERT, bm::BM_SORTED, bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::bmatr_, bm::basic_bmatrix< BV >::construct_row(), bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::get_null_bvect(), bm::basic_bmatrix< BV >::get_row(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::insert_value(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::insert_value_no_null(), bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::plain(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_flags_, bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_matrix2_, bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::set_value(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::set_value_no_null(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::size(), bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::size_, bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::throw_bad_value(), and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::throw_range_error().
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::import(), and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::import_back().
init_remap_buffer()
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> unsigned char* bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::init_remap_buffer () inline protected
Definition at line 1026 of file bmstrsparsevec.h.
References bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_matrix1_.
insert()
template<class CharType , class BV , unsigned MAX_STR_SIZE> void bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::insert (size_type idx, const value_type * str)
insert the specified element
Parameters
idx - element index (vector auto-resized if needs to)
str - string to set (zero terminated)
Definition at line 1094 of file bmstrsparsevec.h.
References bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::insert_value(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::set_value(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::size(), and bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::size_.
Referenced by insertion_sort(), and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::operator[]().
insert_value()
template<class CharType , class BV , unsigned MAX_STR_SIZE> void bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::insert_value (size_type idx, const value_type * str) protected
insert value without checking boundaries
Definition at line 1152 of file bmstrsparsevec.h.
References bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::get_null_bvect(), and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::insert_value_no_null().
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::import_no_check(), and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::insert().
insert_value_no_null()
template<class CharType , class BV , unsigned MAX_STR_SIZE> void bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::insert_value_no_null (size_type idx, const value_type * str) protected
insert value without checking boundaries or support of NULL
Definition at line 1164 of file bmstrsparsevec.h.
References BM_ASSERT, bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::bmatr_, bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::insert_clear_value_plains_from(), bm::basic_bmatrix< BV >::insert_octet(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_flags_, and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_matrix2_.
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::import_no_check(), and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::insert_value().
is_compressed()
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> static bool bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::is_compressed () inline static
trait if sparse vector is "compressed" (false)
Definition at line 698 of file bmstrsparsevec.h.
is_remap()
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> bool bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::is_remap () const inline
Get remapping status (true|false)
Definition at line 713 of file bmstrsparsevec.h.
References bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::build_octet_remap(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::calc_octet_stat(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_flags_, bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_from(), and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_tosv().
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_from().
max_str()
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> static size_type bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::max_str () inline static
get maximum string length capacity
Returns
maximum string length sparse vector can take
Definition at line 618 of file bmstrsparsevec.h.
References bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::effective_max_str(), and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::sv_octet_plains.
operator=() [1/2]
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> str_sparse_vector<CharType, BV, MAX_STR_SIZE>& bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::operator= (const str_sparse_vector< CharType, BV, MAX_STR_SIZE > & str_sv) inline
copy assignmment operator
Definition at line 376 of file bmstrsparsevec.h.
References bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::copy_from(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_flags_, bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_matrix1_, and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_matrix2_.
operator=() [2/2]
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> str_sparse_vector<CharType, BV, MAX_STR_SIZE>& bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::operator= (str_sparse_vector< CharType, BV, MAX_STR_SIZE > && str_sv) inline
move assignmment operator
Definition at line 398 of file bmstrsparsevec.h.
References bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::swap().
operator[]() [1/2]
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> reference bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::operator[] (size_type idx) inline
Operator to get write access to an element.
Definition at line 415 of file bmstrsparsevec.h.
operator[]() [2/2]
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> const_reference bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::operator[] (size_type idx) const inline
Operator to get read access to an element.
Definition at line 418 of file bmstrsparsevec.h.
References bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::insert().
optimize()
template<class CharType , class BV , unsigned MAX_STR_SIZE> void bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::optimize (bm::word_t * temp_block = 0, typename bvector_type::optmode opt_mode = bvector_type::opt_compress, typename str_sparse_vector< CharType, BV, MAX_STR_SIZE >::statistics * stat = 0)
run memory optimization for all vector plains
Parameters
temp_block - pre-allocated memory block to avoid unnecessary re-allocs
opt_mode - requested compression depth
stat - memory allocation statistics after optimization
Examples:
xsample05.cpp.
Definition at line 1224 of file bmstrsparsevec.h.
References bm::bv_statistics::bit_blocks, bm::bv_statistics::gap_blocks, bm::bv_statistics::max_serialize_mem, bm::bv_statistics::memory_used, and bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::optimize().
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::effective_vector_max(), and main().
push_back() [1/2]
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> template<typename StrType > void bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::push_back (const StrType & str) inline
push back a string
Parameters
str - string to set (STL class with size() support, like basic_string)
Examples:
xsample05.cpp.
Definition at line 496 of file bmstrsparsevec.h.
References bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::assign(), and bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::size_.
Referenced by main().
push_back() [2/2]
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> void bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::push_back (const value_type * str) inline
push back a string (zero terminated)
Parameters
str - string to set
Definition at line 502 of file bmstrsparsevec.h.
References bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::size_.
recalc_remap_matrix2()
template<class CharType , class BV , unsigned MAX_STR_SIZE> void bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::recalc_remap_matrix2 ()
re-calculate remap matrix2 based on matrix1
Definition at line 1417 of file bmstrsparsevec.h.
References BM_ASSERT, bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_flags_, bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_matrix1_, and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_matrix2_.
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_tosv(), and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::sync().
remap_from()
template<class CharType , class BV , unsigned MAX_STR_SIZE> void bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_from (const str_sparse_vector< CharType, BV, MAX_STR_SIZE > & str_sv)
Build remapping profile and load content from another sparse vector.
Parameters
str_sv - source sparse vector (assumed it is not remapped)
Examples:
xsample05.cpp.
Definition at line 1499 of file bmstrsparsevec.h.
References bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::build_octet_remap(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::calc_octet_stat(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::clear(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::decode(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::empty(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::is_remap(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_flags_, bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_matrix1_, and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_matrix2_.
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::is_remap(), and main().
remap_fromsv()
template<class CharType , class BV , unsigned MAX_STR_SIZE> bool bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_fromsv (value_type * str, size_type buf_size, const value_type * sv_str, const plain_octet_matrix_type & octet_remap_matrix1) static
remap string from internal code to external (ASCII) system
Returns
true if remapping was ok, false if found incorrect value for the plain
Definition at line 1471 of file bmstrsparsevec.h.
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_tosv().
remap_size()
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> size_t bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_size () const inline protected
Definition at line 1023 of file bmstrsparsevec.h.
References bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_matrix1_.
remap_tosv() [1/2]
template<class CharType , class BV , unsigned MAX_STR_SIZE> bool bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_tosv (value_type * sv_str, size_type buf_size, const value_type * str, const plain_octet_matrix_type & octet_remap_matrix2) static
remap string from external (ASCII) system to matrix internal code
Returns
true if remapping was ok, false if found incorrect value for the plain
Definition at line 1443 of file bmstrsparsevec.h.
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::is_remap(), and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_tosv().
remap_tosv() [2/2]
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> bool bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_tosv (value_type * sv_str, size_type buf_size, const value_type * str) const inline
remap string from external (ASCII) system to matrix internal code
Definition at line 748 of file bmstrsparsevec.h.
References bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::recalc_remap_matrix2(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_fromsv(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_matrix2_, and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_tosv().
resize()
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> void bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::resize (size_type sz) inline
resize vector
Parameters
sz - new size
Definition at line 613 of file bmstrsparsevec.h.
References bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::resize().
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::resize_internal().
resize_internal()
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> void bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::resize_internal (size_type sz) inline protected
Definition at line 1021 of file bmstrsparsevec.h.
References bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::resize().
set()
template<class CharType , class BV , unsigned MAX_STR_SIZE> void bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::set (size_type idx, const value_type * str)
set specified element with bounds checking and automatic resize
Parameters
idx - element index (vector auto-resized if needs to)
str - string to set (zero terminated)
Definition at line 1083 of file bmstrsparsevec.h.
References bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::set_value(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::size(), and bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::size_.
Referenced by main().
set_remap()
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> void bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::set_remap () inline protected
Definition at line 1031 of file bmstrsparsevec.h.
References bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_flags_.
set_value()
template<class CharType , class BV , unsigned MAX_STR_SIZE> void bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::set_value (size_type idx, const value_type * str) protected
set value without checking boundaries
Definition at line 1110 of file bmstrsparsevec.h.
References bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::get_null_bvect(), and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::set_value_no_null().
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::import_no_check(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::insert(), and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::set().
set_value_no_null()
template<class CharType , class BV , unsigned MAX_STR_SIZE> void bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::set_value_no_null (size_type idx, const value_type * str) protected
set value without checking boundaries or support of NULL
Definition at line 1122 of file bmstrsparsevec.h.
References BM_ASSERT, bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::bmatr_, bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::clear_value_plains_from(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_flags_, bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_matrix2_, and bm::basic_bmatrix< BV >::set_octet().
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::import_no_check(), and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::set_value().
size()
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> size_type bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::size () const inline
return size of the vector
Returns
size of sparse vector
Examples:
xsample05.cpp.
Definition at line 603 of file bmstrsparsevec.h.
References bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::size_.
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::back_insert_iterator::add(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::const_iterator::advance(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::assign(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::calc_octet_stat(), check_sparse(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::const_iterator::const_iterator(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::decode(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::effective_size(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::empty(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::const_iterator::go_to(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::import_back(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::import_no_check(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::insert(), main(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::set(), and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::size_internal().
size_internal()
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> size_type bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::size_internal () const inline protected
Definition at line 1020 of file bmstrsparsevec.h.
References bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::size().
swap()
template<class CharType , class BV , unsigned MAX_STR_SIZE> void bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::swap (str_sparse_vector< CharType, BV, MAX_STR_SIZE > & str_sv)
Swap content
Examples:
xsample05.cpp.
Definition at line 1072 of file bmstrsparsevec.h.
References bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_flags_, bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_matrix1_, bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_matrix2_, bm::base_sparse_vector< CharType, BV, MAX_STR_SIZE >::swap(), and bm::xor_swap().
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::get(), main(), and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::operator=().
sync()
template<class CharType , class BV , unsigned MAX_STR_SIZE> void bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::sync (bool force)
syncronize internal structures
Definition at line 1539 of file bmstrsparsevec.h.
References bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::recalc_remap_matrix2(), and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_flags_.
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::import_back().
throw_bad_value()
template<class CharType , class BV , unsigned MAX_STR_SIZE> void bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::throw_bad_value (const char * err_msg) static protected
throw domain error
Definition at line 1609 of file bmstrsparsevec.h.
References BM_ASSERT_THROW.
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::compare(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::get(), and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::import_no_check().
throw_range_error()
template<class CharType , class BV , unsigned MAX_STR_SIZE> void bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::throw_range_error (const char * err_msg) static protected
throw range error
Definition at line 1596 of file bmstrsparsevec.h.
References BM_ASSERT_THROW.
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::import_no_check().
Friends And Related Function Documentation
sparse_vector_deserializer
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> template<class SVect > friend class sparse_vector_deserializer friend
Definition at line 1035 of file bmstrsparsevec.h.
sparse_vector_serializer
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> template<class SVect > friend class sparse_vector_serializer friend
Definition at line 1034 of file bmstrsparsevec.h.
Field Documentation
remap_flags_
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> unsigned bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_flags_ protected
remapping status
Definition at line 1038 of file bmstrsparsevec.h.
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::assign(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::calc_stat(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::compare(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::decode(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::equal(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::get(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::import_no_check(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::insert_value_no_null(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::is_remap(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::operator=(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::recalc_remap_matrix2(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_from(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::set_remap(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::set_value_no_null(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::str_sparse_vector(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::swap(), and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::sync().
remap_matrix1_
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> plain_octet_matrix_type bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_matrix1_ protected
octet remap table 1
Definition at line 1039 of file bmstrsparsevec.h.
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::calc_stat(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::decode(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::equal(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::get(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::get_remap_buffer(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::init_remap_buffer(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::operator=(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::recalc_remap_matrix2(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_from(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_size(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::str_sparse_vector(), and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::swap().
remap_matrix2_
template<typename CharType, typename BV, unsigned MAX_STR_SIZE> plain_octet_matrix_type bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_matrix2_ protected
octet remap table 2
Definition at line 1040 of file bmstrsparsevec.h.
Referenced by bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::assign(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::calc_stat(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::compare(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::equal(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::import_no_check(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::insert_value_no_null(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::operator=(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::recalc_remap_matrix2(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_from(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_tosv(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::set_value_no_null(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::str_sparse_vector(), and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::swap().
The documentation for this class was generated from the following file:
bmstrsparsevec.h