BitMagic-C++: bm::bvector< Alloc >::iterator_base Class Reference
bm::bvector< Alloc >::iterator_base Class Reference
BitMagic Library » bvector<> container » bvector<> iterators
Base class for all iterators.
#include <bm.h>
Data Structures
struct bitblock_descr
Information about current bitblock.
union block_descr
struct dgap_descr
Information about current DGAP block.
Public Member Functions
iterator_base ()
bool operator== (const iterator_base &it) const
bool operator!= (const iterator_base &it) const
bool operator< (const iterator_base &it) const
bool operator<= (const iterator_base &it) const
bool operator> (const iterator_base &it) const
bool operator>= (const iterator_base &it) const
bool valid () const
Checks if iterator is still valid.
void invalidate ()
Turns iterator into an invalid state.
bool compare_state (const iterator_base &ib) const
Compare FSMs for testing purposes.
Protected Attributes
bm::bvector< Alloc > * bv_
Pointer on parent bitvector.
bm::id_t position_
Bit position (bit idx)
const bm::word_t * block_
Block pointer.(NULL-invalid)
unsigned block_type_
Type of block. 0-Bit, 1-GAP.
unsigned block_idx_
Block index.
union bm::bvector::iterator_base::block_descr bdescr_
Friends
class bvector
Detailed Description
template<class Alloc>
class bm::bvector< Alloc >::iterator_base
Base class for all iterators.
Definition at line 259 of file bm.h.
Constructor & Destructor Documentation
iterator_base()
template<class Alloc> bm::bvector< Alloc >::iterator_base::iterator_base () inline
Definition at line 263 of file bm.h.
Member Function Documentation
compare_state()
template<class Alloc> bool bm::bvector< Alloc >::iterator_base::compare_state (const iterator_base & ib) const inline
Compare FSMs for testing purposes.
Definition at line 311 of file bm.h.
References bm::bvector< Alloc >::iterator_base::bdescr_, bm::bvector< Alloc >::iterator_base::block_descr::bit_, bm::bvector< Alloc >::iterator_base::bitblock_descr::bits, bm::bvector< Alloc >::iterator_base::block_, bm::bvector< Alloc >::iterator_base::block_idx_, bm::bvector< Alloc >::iterator_base::block_type_, bm::bvector< Alloc >::iterator_base::bv_, bm::bvector< Alloc >::iterator_base::bitblock_descr::cnt, bm::bvector< Alloc >::iterator_base::block_descr::gap_, bm::bvector< Alloc >::iterator_base::dgap_descr::gap_len, bm::bvector< Alloc >::iterator_base::bitblock_descr::idx, bm::bvector< Alloc >::iterator_base::bitblock_descr::pos, bm::bvector< Alloc >::iterator_base::position_, bm::bvector< Alloc >::iterator_base::bitblock_descr::ptr, and bm::bvector< Alloc >::iterator_base::dgap_descr::ptr.
invalidate()
template<class Alloc> bool bm::bvector< Alloc >::iterator_base::invalidate () inline
Turns iterator into an invalid state.
Definition at line 306 of file bm.h.
References bm::id_max.
operator!=()
template<class Alloc> bool bm::bvector< Alloc >::iterator_base::operator!= (const iterator_base & it) const inline
Definition at line 270 of file bm.h.
operator<()
template<class Alloc> bool bm::bvector< Alloc >::iterator_base::operator< (const iterator_base & it) const inline
Definition at line 275 of file bm.h.
References bm::bvector< Alloc >::iterator_base::position_.
operator<=()
template<class Alloc> bool bm::bvector< Alloc >::iterator_base::operator<= (const iterator_base & it) const inline
Definition at line 280 of file bm.h.
References bm::bvector< Alloc >::iterator_base::position_.
operator==()
template<class Alloc> bool bm::bvector< Alloc >::iterator_base::operator== (const iterator_base & it) const inline
Definition at line 265 of file bm.h.
References bm::bvector< Alloc >::iterator_base::bv_, and bm::bvector< Alloc >::iterator_base::position_.
operator>()
template<class Alloc> bool bm::bvector< Alloc >::iterator_base::operator> (const iterator_base & it) const inline
Definition at line 285 of file bm.h.
References bm::bvector< Alloc >::iterator_base::position_.
operator>=()
template<class Alloc> bool bm::bvector< Alloc >::iterator_base::operator>= (const iterator_base & it) const inline
Definition at line 290 of file bm.h.
References bm::bvector< Alloc >::iterator_base::position_.
valid()
template<class Alloc> bool bm::bvector< Alloc >::iterator_base::valid () const inline
Checks if iterator is still valid.
Analog of != 0 comparison for pointers.
Returns
true if iterator is valid.
Examples:
bvsetalgebra.cpp, sample11.cpp, sample5.cpp, svsample04.cpp, svsample05.cpp, svsample06.cpp, xsample01.cpp, xsample03.cpp, and xsample04.cpp.
Definition at line 300 of file bm.h.
References bm::id_max.
Referenced by bv2delta(), bv_counted_enumerator(), convert_bv2sv(), convert_bv2vect(), bm::rsc_sparse_vector< Val, SV >::decode(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::decode(), generate_random_subset(), main(), print_bvector(), speed_test_bv_index(), speed_test_bvs_index(), speed_test_sv_index(), speed_test_vect_index(), and DNA_FingerprintScanner::TranslateResults().
Friends And Related Function Documentation
bvector
template<class Alloc> friend class bvector friend
Definition at line 261 of file bm.h.
Field Documentation
bdescr_
template<class Alloc> union bm::bvector::iterator_base::block_descr bm::bvector< Alloc >::iterator_base::bdescr_ protected
Referenced by bm::bvector< Alloc >::iterator_base::compare_state().
block_
template<class Alloc> const bm::word_t* bm::bvector< Alloc >::iterator_base::block_ protected
Block pointer.(NULL-invalid)
Definition at line 363 of file bm.h.
Referenced by bm::bvector< Alloc >::iterator_base::compare_state().
block_idx_
template<class Alloc> unsigned bm::bvector< Alloc >::iterator_base::block_idx_ protected
Block index.
Definition at line 365 of file bm.h.
Referenced by bm::bvector< Alloc >::iterator_base::compare_state().
block_type_
template<class Alloc> unsigned bm::bvector< Alloc >::iterator_base::block_type_ protected
Type of block. 0-Bit, 1-GAP.
Definition at line 364 of file bm.h.
Referenced by bm::bvector< Alloc >::iterator_base::compare_state().
bv_
template<class Alloc> bm::bvector<Alloc>* bm::bvector< Alloc >::iterator_base::bv_ protected
Pointer on parent bitvector.
Definition at line 361 of file bm.h.
Referenced by bm::bvector< Alloc >::iterator_base::compare_state(), and bm::bvector< Alloc >::iterator_base::operator==().
position_
template<class Alloc> bm::id_t bm::bvector< Alloc >::iterator_base::position_ protected
Bit position (bit idx)
Definition at line 362 of file bm.h.
Referenced by bm::bvector< Alloc >::iterator_base::compare_state(), bm::bvector< Alloc >::iterator_base::operator<(), bm::bvector< Alloc >::iterator_base::operator<=(), bm::bvector< Alloc >::iterator_base::operator==(), bm::bvector< Alloc >::iterator_base::operator>(), and bm::bvector< Alloc >::iterator_base::operator>=().
The documentation for this class was generated from the following file:
bm.h