BitMagic-C++: bm::bitblock_sum_adapter Class Reference
bm::bitblock_sum_adapter Class Reference
Bit-block sum adapter, takes values and sums it /internal.
#include <bmfunc.h>
Public Member Functions
bitblock_sum_adapter ()
BMFORCEINLINE void push_back (bm::word_t w)
bm::word_t sum () const
Get accumulated sum.
Detailed Description
Bit-block sum adapter, takes values and sums it /internal.
Definition at line 6779 of file bmfunc.h.
Constructor & Destructor Documentation
bitblock_sum_adapter()
bm::bitblock_sum_adapter::bitblock_sum_adapter () inline
Definition at line 6782 of file bmfunc.h.
References BMFORCEINLINE.
Member Function Documentation
push_back()
BMFORCEINLINE void bm::bitblock_sum_adapter::push_back (bm::word_t w) inline
Definition at line 6784 of file bmfunc.h.
sum()
bm::word_t bm::bitblock_sum_adapter::sum () const inline
Get accumulated sum.
Definition at line 6786 of file bmfunc.h.
Referenced by bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_OR(), bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_SUB_AB(), bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_SUB_BA(), and bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_XOR().
The documentation for this class was generated from the following file:
bmfunc.h