BitMagic-C++: bm::bvector< Alloc >::enumerator Class Reference
bm::bvector< Alloc >::enumerator Class Reference
BitMagic Library » bvector<> container » bvector<> iterators
Constant iterator designed to enumerate "ON" bits.
#include <bm.h>
Public Types
typedef std::input_iterator_tag iterator_category
typedef unsigned value_type
typedef unsigned difference_type
typedef unsigned * pointer
typedef unsigned & reference
Public Member Functions
enumerator ()
enumerator (const bvector< Alloc > *bv)
Construct enumerator associated with a vector. This construction creates unpositioned iterator with status valid() == false. It can be re-positioned using go_first() or go_to()
enumerator (const bvector< Alloc > *bv, bm::id_t pos)
Construct enumerator for bit vector.
bm::id_t operator* () const
Get current position (value)
bm::id_t value () const
Get current position (value)
enumerator & operator++ ()
Advance enumerator forward to the next available bit.
enumerator operator++ (int)
Advance enumerator forward to the next available bit. Possibly do NOT use this operator it is slower than the pre-fix increment.
void go_first ()
Position enumerator to the first available bit.
void advance ()
advance iterator forward by one
enumerator & go_up ()
Advance enumerator to the next available bit.
enumerator & skip_to_rank (bm::id_t rank)
Skip to specified relative rank.
enumerator & skip (bm::id_t rank)
Skip specified number of bits from enumeration.
enumerator & go_to (bm::id_t pos)
go to a specific position in the bit-vector (or next)
Public Member Functions inherited from bm::bvector< Alloc >::iterator_base
iterator_base ()
bool operator== (const iterator_base &it) const
bool operator!= (const iterator_base &it) const
bool operator< (const iterator_base &it) const
bool operator<= (const iterator_base &it) const
bool operator> (const iterator_base &it) const
bool operator>= (const iterator_base &it) const
bool valid () const
Checks if iterator is still valid.
void invalidate ()
Turns iterator into an invalid state.
bool compare_state (const iterator_base &ib) const
Compare FSMs for testing purposes.
Additional Inherited Members
Protected Attributes inherited from bm::bvector< Alloc >::iterator_base
bm::bvector< Alloc > * bv_
Pointer on parent bitvector.
bm::id_t position_
Bit position (bit idx)
const bm::word_t * block_
Block pointer.(NULL-invalid)
unsigned block_type_
Type of block. 0-Bit, 1-GAP.
unsigned block_idx_
Block index.
union bm::bvector::iterator_base::block_descr bdescr_
Detailed Description
template<class Alloc>
class bm::bvector< Alloc >::enumerator
Constant iterator designed to enumerate "ON" bits.
Examples:
bvsetalgebra.cpp, sample5.cpp, sample8.cpp, svsample04.cpp, svsample05.cpp, svsample06.cpp, xsample01.cpp, xsample03.cpp, and xsample04.cpp.
Definition at line 601 of file bm.h.
Member Typedef Documentation
difference_type
template<class Alloc> typedef unsigned bm::bvector< Alloc >::enumerator::difference_type
Definition at line 608 of file bm.h.
iterator_category
template<class Alloc> typedef std::input_iterator_tag bm::bvector< Alloc >::enumerator::iterator_category
Definition at line 605 of file bm.h.
pointer
template<class Alloc> typedef unsigned* bm::bvector< Alloc >::enumerator::pointer
Definition at line 609 of file bm.h.
reference
template<class Alloc> typedef unsigned& bm::bvector< Alloc >::enumerator::reference
Definition at line 610 of file bm.h.
value_type
template<class Alloc> typedef unsigned bm::bvector< Alloc >::enumerator::value_type
Definition at line 607 of file bm.h.
Constructor & Destructor Documentation
enumerator() [1/3]
template<class Alloc> bm::bvector< Alloc >::enumerator::enumerator () inline
Definition at line 613 of file bm.h.
enumerator() [2/3]
template<class Alloc> bm::bvector< Alloc >::enumerator::enumerator (const bvector< Alloc > * bv) inline
Construct enumerator associated with a vector. This construction creates unpositioned iterator with status valid() == false. It can be re-positioned using go_first() or go_to()
Definition at line 620 of file bm.h.
enumerator() [3/3]
template<class Alloc> bm::bvector< Alloc >::enumerator::enumerator (const bvector< Alloc > * bv, bm::id_t pos) inline
Construct enumerator for bit vector.
Parameters
bv bit-vector pointer
pos bit position in the vector if position is 0, it finds the next 1 or becomes not valid (en.valid() == false)
Definition at line 632 of file bm.h.
Member Function Documentation
advance()
template<class Alloc> void bm::bvector< Alloc >::enumerator::advance () inline
advance iterator forward by one
Definition at line 725 of file bm.h.
Referenced by bm::rsc_sparse_vector< Val, SV >::decode().
go_first()
template<class Alloc> void bm::bvector< Alloc >::enumerator::go_first () inline
Position enumerator to the first available bit.
Definition at line 660 of file bm.h.
References bm::bits_in_array, bm::bits_in_block, BM_ASSERT, BM_IS_GAP, FULL_BLOCK_FAKE_ADDR, FULL_BLOCK_REAL_ADDR, and bm::set_array_size.
go_to()
template<class Alloc> enumerator& bm::bvector< Alloc >::enumerator::go_to (bm::id_t pos) inline
go to a specific position in the bit-vector (or next)
Examples:
sample5.cpp.
Definition at line 887 of file bm.h.
References bm::bvector< Alloc >::iterator_base::block_descr::bit_, bm::bvector< Alloc >::iterator_base::bitblock_descr::bits, bm::bits_in_array, bm::bits_in_block, bm::bitscan_wave(), BM_ASSERT, BM_IS_GAP, BMGAP_PTR, bm::bvector< Alloc >::iterator_base::bitblock_descr::cnt, FULL_BLOCK_FAKE_ADDR, FULL_BLOCK_REAL_ADDR, bm::bvector< Alloc >::iterator_base::block_descr::gap_, bm::gap_bfind(), bm::bvector< Alloc >::iterator_base::dgap_descr::gap_len, bm::gap_max_bits, bm::bvector< Alloc >::iterator_base::bitblock_descr::idx, bm::bvector< Alloc >::iterator_base::bitblock_descr::pos, bm::bvector< Alloc >::iterator_base::bitblock_descr::ptr, bm::bvector< Alloc >::iterator_base::dgap_descr::ptr, bm::set_array_mask, bm::set_array_shift, bm::set_array_size, bm::set_bitscan_wave_size, bm::set_block_mask, bm::set_block_shift, bm::set_block_size, bm::set_word_mask, bm::set_word_shift, and bm::word_bitcount64().
Referenced by main().
go_up()
template<class Alloc> enumerator& bm::bvector< Alloc >::enumerator::go_up () inline
Advance enumerator to the next available bit.
Definition at line 729 of file bm.h.
References bm::bvector< Alloc >::iterator_base::block_descr::bit_, bm::bvector< Alloc >::iterator_base::bitblock_descr::bits, BM_ASSERT, BM_ASSERT_THROW, bm::bvector< Alloc >::iterator_base::block_descr::gap_, bm::bvector< Alloc >::iterator_base::dgap_descr::gap_len, bm::gap_max_bits, bm::bvector< Alloc >::iterator_base::bitblock_descr::idx, bm::bvector< Alloc >::iterator_base::bitblock_descr::pos, bm::bvector< Alloc >::iterator_base::bitblock_descr::ptr, bm::bvector< Alloc >::iterator_base::dgap_descr::ptr, and bm::set_bitscan_wave_size.
operator*()
template<class Alloc> bm::id_t bm::bvector< Alloc >::enumerator::operator* () const inline
Get current position (value)
Definition at line 640 of file bm.h.
operator++() [1/2]
template<class Alloc> enumerator& bm::bvector< Alloc >::enumerator::operator++ () inline
Advance enumerator forward to the next available bit.
Definition at line 646 of file bm.h.
operator++() [2/2]
template<class Alloc> enumerator bm::bvector< Alloc >::enumerator::operator++ (int) inline
Advance enumerator forward to the next available bit. Possibly do NOT use this operator it is slower than the pre-fix increment.
Definition at line 651 of file bm.h.
skip()
template<class Alloc> enumerator& bm::bvector< Alloc >::enumerator::skip (bm::id_t rank) inline
Skip specified number of bits from enumeration.
Parameters
rank - number of ON bits to skip
Definition at line 814 of file bm.h.
References bm::bvector< Alloc >::iterator_base::block_descr::bit_, bm::bvector< Alloc >::iterator_base::bitblock_descr::bits, BM_ASSERT, bm::bvector< Alloc >::iterator_base::block_descr::gap_, bm::bvector< Alloc >::iterator_base::dgap_descr::gap_len, bm::gap_max_bits, bm::bvector< Alloc >::iterator_base::bitblock_descr::idx, bm::bvector< Alloc >::iterator_base::bitblock_descr::pos, bm::bvector< Alloc >::iterator_base::bitblock_descr::ptr, bm::bvector< Alloc >::iterator_base::dgap_descr::ptr, and bm::set_bitscan_wave_size.
skip_to_rank()
template<class Alloc> enumerator& bm::bvector< Alloc >::enumerator::skip_to_rank (bm::id_t rank) inline
Skip to specified relative rank.
Parameters
rank - number of ON bits to go for
Definition at line 802 of file bm.h.
value()
template<class Alloc> bm::id_t bm::bvector< Alloc >::enumerator::value () const inline
Get current position (value)
Definition at line 643 of file bm.h.
The documentation for this class was generated from the following file:
bm.h