BitMagic-C++: bm::decoder Class Reference
bm::decoder Class Reference
Elias Gamma Code (internal)
Class for decoding data from memory buffer.
#include <encoding.h>
Public Member Functions
decoder (const unsigned char *buf)
Construction.
bm::short_t get_16 ()
Reads 16-bit word from the decoding buffer.
bm::word_t get_32 ()
Reads 32-bit word from the decoding buffer.
bm::id64_t get_64 ()
Reads 64-bit word from the decoding buffer.
void get_32 (bm::word_t *w, unsigned count)
Reads block of 32-bit words from the decoding buffer.
bool get_32_OR (bm::word_t *w, unsigned count)
Reads block of 32-bit words from the decoding buffer and ORs to the destination.
void get_32_AND (bm::word_t *w, unsigned count)
Reads block of 32-bit words from the decoding buffer and ANDs to the destination.
void get_16 (bm::short_t *s, unsigned count)
Reads block of 32-bit words from the decoding buffer.
Public Member Functions inherited from bm::decoder_base
decoder_base (const unsigned char *buf)
unsigned char get_8 ()
Reads character from the decoding buffer.
unsigned size () const
Returns size of the current decoding stream.
void seek (int delta)
change current position
void memcpy (unsigned char *dst, size_t count)
read bytes from the decode buffer
const unsigned char * get_pos () const
Return current buffer pointer.
Additional Inherited Members
Protected Attributes inherited from bm::decoder_base
const unsigned char * buf_
const unsigned char * start_
Detailed Description
Class for decoding data from memory buffer.
Properly handles aligment issues with integer data types.
Definition at line 105 of file encoding.h.
Constructor & Destructor Documentation
decoder()
bm::decoder::decoder (const unsigned char * buf) inline
Construction.
Parameters
buf - pointer to the decoding memory.
Definition at line 785 of file encoding.h.
Member Function Documentation
get_16() [1/2]
BMFORCEINLINE bm::short_t bm::decoder::get_16 ()
Reads 16-bit word from the decoding buffer.
Definition at line 794 of file encoding.h.
References bm::decoder_base::buf_.
Referenced by bm::deserializer< typename SV::bvector_type, bm::decoder >::deserialize(), bm::deserializer< typename SV::bvector_type, bm::decoder >::deserialize_gap(), bm::deseriaizer_base< bm::decoder >::read_gap_block(), and bm::deseriaizer_base< bm::decoder >::read_id_list().
get_16() [2/2]
void bm::decoder::get_16 (bm::short_t * s, unsigned count) inline
Reads block of 32-bit words from the decoding buffer.
Parameters
s - pointer on memory block to read into.
count - size of memory block in words.
Definition at line 961 of file encoding.h.
References bm::decoder_base::buf_, and bm::decoder_base::seek().
get_32() [1/2]
BMFORCEINLINE bm::word_t bm::decoder::get_32 ()
Reads 32-bit word from the decoding buffer.
Definition at line 809 of file encoding.h.
References bm::decoder_base::buf_.
Referenced by bm::compressed_collection_deserializer< CBC >::deserialize(), bm::deserializer< typename SV::bvector_type, bm::decoder >::deserialize(), bm::deserializer< typename SV::bvector_type, bm::decoder >::deserialize_gap(), get_32_AND(), and get_32_OR().
get_32() [2/2]
void bm::decoder::get_32 (bm::word_t * w, unsigned count) inline
Reads block of 32-bit words from the decoding buffer.
Parameters
w - pointer on memory block to read into.
count - size of memory block in words.
Definition at line 850 of file encoding.h.
References bm::decoder_base::buf_, bm::decoder_base::memcpy(), and bm::decoder_base::seek().
get_32_AND()
void bm::decoder::get_32_AND (bm::word_t * w, unsigned count) inline
Reads block of 32-bit words from the decoding buffer and ANDs to the destination.
Parameters
w - pointer on memory block to read into
count - should match bm::set_block_size
Definition at line 923 of file encoding.h.
References bm::decoder_base::buf_, get_32(), bm::decoder_base::seek(), and bm::sse2_and_arr_unal().
get_32_OR()
bool bm::decoder::get_32_OR (bm::word_t * w, unsigned count) inline
Reads block of 32-bit words from the decoding buffer and ORs to the destination.
Parameters
w - pointer on memory block to read into
count - should match bm::set_block_size
Definition at line 882 of file encoding.h.
References bm::decoder_base::buf_, get_32(), bm::decoder_base::seek(), and bm::sse2_or_arr_unal().
get_64()
bm::id64_t bm::decoder::get_64 () inline
Reads 64-bit word from the decoding buffer.
Definition at line 825 of file encoding.h.
References bm::decoder_base::buf_.
Referenced by bm::sparse_vector_deserializer< SV >::deserialize(), and bm::compressed_collection_deserializer< CBC >::deserialize().
The documentation for this class was generated from the following file:
encoding.h