BitMagic-C++: bm::sparse_vector_deserializer< SV > Class Template Reference
bm::sparse_vector_deserializer< SV > Class Template Reference
sparse vector de-serializer
#include <bmsparsevec_serial.h>
Public Types
typedef SV::bvector_type bvector_type
typedef const bvector_type * bvector_type_const_ptr
typedef bvector_type * bvector_type_ptr
typedef SV::value_type value_type
typedef SV::size_type size_type
typedef bvector_type::allocator_type::allocator_pool_type allocator_pool_type
Public Member Functions
sparse_vector_deserializer ()
void deserialize (SV &sv, const unsigned char *buf)
Protected Attributes
bm::deserializer< typename SV::bvector_type, bm::decoder > deserial_
Detailed Description
template<typename SV>
class bm::sparse_vector_deserializer< SV >
sparse vector de-serializer
Definition at line 197 of file bmsparsevec_serial.h.
Member Typedef Documentation
allocator_pool_type
template<typename SV> typedef bvector_type::allocator_type::allocator_pool_type bm::sparse_vector_deserializer< SV >::allocator_pool_type
Definition at line 205 of file bmsparsevec_serial.h.
bvector_type
template<typename SV> typedef SV::bvector_type bm::sparse_vector_deserializer< SV >::bvector_type
Definition at line 200 of file bmsparsevec_serial.h.
bvector_type_const_ptr
template<typename SV> typedef const bvector_type* bm::sparse_vector_deserializer< SV >::bvector_type_const_ptr
Definition at line 201 of file bmsparsevec_serial.h.
bvector_type_ptr
template<typename SV> typedef bvector_type* bm::sparse_vector_deserializer< SV >::bvector_type_ptr
Definition at line 202 of file bmsparsevec_serial.h.
size_type
template<typename SV> typedef SV::size_type bm::sparse_vector_deserializer< SV >::size_type
Definition at line 204 of file bmsparsevec_serial.h.
value_type
template<typename SV> typedef SV::value_type bm::sparse_vector_deserializer< SV >::value_type
Definition at line 203 of file bmsparsevec_serial.h.
Constructor & Destructor Documentation
sparse_vector_deserializer()
template<typename SV > bm::sparse_vector_deserializer< SV >::sparse_vector_deserializer ()
Definition at line 621 of file bmsparsevec_serial.h.
Member Function Documentation
deserialize()
template<typename SV > void bm::sparse_vector_deserializer< SV >::deserialize (SV & sv, const unsigned char * buf)
Definition at line 628 of file bmsparsevec_serial.h.
References BM_ASSERT, bm::decoder::get_64(), bm::decoder_base::get_8(), and bm::decoder_base::memcpy().
Referenced by bm::sparse_vector_deserialize().
Field Documentation
deserial_
template<typename SV> bm::deserializer<typename SV::bvector_type, bm::decoder> bm::sparse_vector_deserializer< SV >::deserial_ protected
Definition at line 215 of file bmsparsevec_serial.h.
The documentation for this class was generated from the following file:
bmsparsevec_serial.h