BitMagic-C++: bm::encoder Class Reference
bm::encoder Class Reference
Elias Gamma Code (internal)
Memory encoding.
#include <encoding.h>
Public Types
typedef unsigned char * position_type
Public Member Functions
encoder (unsigned char *buf, size_t size)
Construction.
void put_8 (unsigned char c)
Puts one character into the encoding buffer.
void put_16 (bm::short_t s)
Puts short word (16 bits) into the encoding buffer.
void put_16 (const bm::short_t *s, unsigned count)
Method puts array of short words (16 bits) into the encoding buffer.
void put_32 (bm::word_t w)
Puts 32 bits word into encoding buffer.
void put_32 (const bm::word_t *w, unsigned count)
Encodes array of 32-bit words.
void put_64 (bm::id64_t w)
Puts 64 bits word into encoding buffer.
void put_prefixed_array_32 (unsigned char c, const bm::word_t *w, unsigned count)
Encode 8-bit prefix + an array.
void put_prefixed_array_16 (unsigned char c, const bm::short_t *s, unsigned count, bool encode_count)
Encode 8-bit prefix + an array.
void memcpy (const unsigned char *src, size_t count)
copy bytes into target buffer or just rewind if src is NULL
unsigned size () const
Returns size of the current encoding stream.
unsigned char * get_pos () const
Get current memory stream position.
void set_pos (unsigned char *buf_pos)
Set current memory stream position.
Detailed Description
Memory encoding.
Class for encoding data into memory. Properly handles aligment issues with integer data types.
Definition at line 42 of file encoding.h.
Member Typedef Documentation
position_type
typedef unsigned char* bm::encoder::position_type
Definition at line 45 of file encoding.h.
Constructor & Destructor Documentation
encoder()
bm::encoder::encoder (unsigned char * buf, size_t size) inline
Construction.
Parameters
buf - memory buffer pointer.
size - size of the buffer
Definition at line 559 of file encoding.h.
Member Function Documentation
get_pos()
encoder::position_type bm::encoder::get_pos () const inline
Get current memory stream position.
Definition at line 674 of file encoding.h.
Referenced by bm::serializer< bvector_type >::gamma_gap_array(), and bm::serializer< bvector_type >::gamma_gap_block().
memcpy()
void bm::encoder::memcpy (const unsigned char * src, size_t count) inline
copy bytes into target buffer or just rewind if src is NULL
Definition at line 653 of file encoding.h.
References BM_ASSERT.
Referenced by bm::decoder_base::memcpy(), bm::decoder_base::seek(), and bm::sparse_vector_serializer< SV >::serialize().
put_16() [1/2]
BMFORCEINLINE void bm::encoder::put_16 (bm::short_t s)
Puts short word (16 bits) into the encoding buffer.
Parameters
s - short word to encode
Definition at line 605 of file encoding.h.
Referenced by bm::serializer< bvector_type >::encode_bit_interval(), bm::serializer< bvector_type >::encode_gap_block(), bm::serializer< bvector_type >::encode_header(), bm::serializer< bvector_type >::gamma_gap_block(), put_prefixed_array_16(), and bm::serializer< bvector_type >::serialize().
put_16() [2/2]
void bm::encoder::put_16 (const bm::short_t * s, unsigned count) inline
Method puts array of short words (16 bits) into the encoding buffer.
Definition at line 620 of file encoding.h.
put_32() [1/2]
void bm::encoder::put_32 (bm::word_t w) inline
Puts 32 bits word into encoding buffer.
Parameters
w - word to encode.
Definition at line 693 of file encoding.h.
Referenced by bm::serializer< bvector_type >::encode_bit_interval(), bm::serializer< bvector_type >::encode_header(), and put_prefixed_array_32().
put_32() [2/2]
void bm::encoder::put_32 (const bm::word_t * w, unsigned count) inline
Encodes array of 32-bit words.
Definition at line 733 of file encoding.h.
put_64()
void bm::encoder::put_64 (bm::id64_t w) inline
Puts 64 bits word into encoding buffer.
Parameters
w - word to encode.
Definition at line 711 of file encoding.h.
Referenced by bm::sparse_vector_serializer< SV >::serialize().
put_8()
BMFORCEINLINE void bm::encoder::put_8 (unsigned char c)
Puts one character into the encoding buffer.
Parameters
c - character to encode
Definition at line 595 of file encoding.h.
Referenced by bm::serializer< bvector_type >::encode_bit_interval(), bm::serializer< bvector_type >::encode_gap_block(), bm::serializer< bvector_type >::encode_header(), bm::serializer< bvector_type >::gamma_gap_array(), bm::serializer< bvector_type >::gamma_gap_block(), put_prefixed_array_16(), put_prefixed_array_32(), bm::sparse_vector_serializer< SV >::serialize(), and bm::serializer< bvector_type >::serialize().
put_prefixed_array_16()
void bm::encoder::put_prefixed_array_16 (unsigned char c, const bm::short_t * s, unsigned count, bool encode_count) inline
Encode 8-bit prefix + an array.
Definition at line 578 of file encoding.h.
References put_16(), and put_8().
Referenced by bm::serializer< bvector_type >::gamma_gap_array().
put_prefixed_array_32()
void bm::encoder::put_prefixed_array_32 (unsigned char c, const bm::word_t * w, unsigned count) inline
Encode 8-bit prefix + an array.
Definition at line 567 of file encoding.h.
References put_32(), and put_8().
Referenced by bm::serializer< bvector_type >::serialize().
set_pos()
void bm::encoder::set_pos (unsigned char * buf_pos) inline
Set current memory stream position.
Definition at line 682 of file encoding.h.
Referenced by bm::serializer< bvector_type >::gamma_gap_array(), and bm::serializer< bvector_type >::gamma_gap_block().
size()
unsigned bm::encoder::size () const inline
Returns size of the current encoding stream.
Definition at line 666 of file encoding.h.
Referenced by bm::sparse_vector_serializer< SV >::serialize(), and bm::serializer< bvector_type >::serialize().
The documentation for this class was generated from the following file:
encoding.h