BitMagic-C++: bm::decoder_little_endian Class Reference
bm::decoder_little_endian Class Reference
Elias Gamma Code (internal)
Class for decoding data from memory buffer.
#include <encoding.h>
Public Member Functions
decoder_little_endian (const unsigned char *buf)
bm::short_t get_16 ()
bm::word_t get_32 ()
void get_32 (bm::word_t *w, unsigned count)
bool get_32_OR (bm::word_t *w, unsigned count)
void get_32_AND (bm::word_t *w, unsigned count)
void get_16 (bm::short_t *s, unsigned count)
Public Member Functions inherited from bm::decoder_base
decoder_base (const unsigned char *buf)
unsigned char get_8 ()
Reads character from the decoding buffer.
unsigned size () const
Returns size of the current decoding stream.
void seek (int delta)
change current position
void memcpy (unsigned char *dst, size_t count)
read bytes from the decode buffer
const unsigned char * get_pos () const
Return current buffer pointer.
Additional Inherited Members
Protected Attributes inherited from bm::decoder_base
const unsigned char * buf_
const unsigned char * start_
Detailed Description
Class for decoding data from memory buffer.
Properly handles aligment issues with integer data types. Converts data to little endian architecture (presumed it was encoded as big endian)
Definition at line 137 of file encoding.h.
Constructor & Destructor Documentation
decoder_little_endian()
bm::decoder_little_endian::decoder_little_endian (const unsigned char * buf) inline
Definition at line 992 of file encoding.h.
References BMFORCEINLINE.
Member Function Documentation
get_16() [1/2]
BMFORCEINLINE bm::short_t bm::decoder_little_endian::get_16 ()
Definition at line 998 of file encoding.h.
References BMFORCEINLINE, and bm::decoder_base::buf_.
get_16() [2/2]
void bm::decoder_little_endian::get_16 (bm::short_t * s, unsigned count) inline
Definition at line 1073 of file encoding.h.
References bm::decoder_base::buf_, and bm::decoder_base::seek().
get_32() [1/2]
BMFORCEINLINE bm::word_t bm::decoder_little_endian::get_32 ()
Definition at line 1008 of file encoding.h.
References bm::decoder_base::buf_.
Referenced by get_32_AND(), and get_32_OR().
get_32() [2/2]
void bm::decoder_little_endian::get_32 (bm::word_t * w, unsigned count) inline
Definition at line 1017 of file encoding.h.
References bm::decoder_base::buf_, and bm::decoder_base::seek().
get_32_AND()
void bm::decoder_little_endian::get_32_AND (bm::word_t * w, unsigned count) inline
Definition at line 1060 of file encoding.h.
References get_32().
get_32_OR()
bool bm::decoder_little_endian::get_32_OR (bm::word_t * w, unsigned count) inline
Definition at line 1038 of file encoding.h.
References get_32(), and bm::decoder_base::seek().
The documentation for this class was generated from the following file:
encoding.h