BitMagic-C++: bm::serial_stream_iterator< DEC > Class Template Reference
bm::serial_stream_iterator< DEC > Class Template Reference
BitMagic Library » bvector<> container » bvector<> serialization
Serialization stream iterator.
#include <bmserial.h>
Public Types
enum iterator_state {
e_unknown = 0, e_list_ids, e_blocks, e_zero_blocks,
e_one_blocks, e_bit_block, e_gap_block
}
iterator is a state machine, this enum encodes its key value
typedef deseriaizer_base< DEC >::decoder_type decoder_type
typedef unsigned(serial_stream_iterator< DEC >::* get_bit_func_type) (bm::word_t *, bm::word_t *)
member function pointer for bitset-bitset get operations
Public Member Functions
serial_stream_iterator (const unsigned char *buf)
unsigned bv_size () const
serialized bitvector size
bool is_eof () const
Returns true if end of bit-stream reached.
void next ()
get next block
void skip_mono_blocks ()
skip all zero or all-one blocks
unsigned get_bit_block (bm::word_t *dst_block, bm::word_t *tmp_block, set_operation op)
read bit block, using logical operation
void get_gap_block (bm::gap_word_t *dst_block)
Read gap block data (with head)
unsigned dec_size () const
Return current decoder size.
decoder_type & decoder ()
Get low level access to the decoder (use carefully)
iterator_state state () const
Returns iterator internal state.
iterator_state get_state () const
unsigned get_id_count () const
Number of ids in the inverted list (valid for e_list_ids)
bm::id_t get_id () const
Get last id from the id list.
unsigned block_idx () const
Get current block index.
unsigned get_bit_block_ASSIGN (bm::word_t *dst_block, bm::word_t *tmp_block)
unsigned get_bit_block_OR (bm::word_t *dst_block, bm::word_t *tmp_block)
unsigned get_bit_block_AND (bm::word_t *dst_block, bm::word_t *tmp_block)
unsigned get_bit_block_SUB (bm::word_t *dst_block, bm::word_t *tmp_block)
unsigned get_bit_block_XOR (bm::word_t *dst_block, bm::word_t *tmp_block)
unsigned get_bit_block_COUNT (bm::word_t *dst_block, bm::word_t *tmp_block)
unsigned get_bit_block_COUNT_AND (bm::word_t *dst_block, bm::word_t *tmp_block)
unsigned get_bit_block_COUNT_OR (bm::word_t *dst_block, bm::word_t *tmp_block)
unsigned get_bit_block_COUNT_XOR (bm::word_t *dst_block, bm::word_t *tmp_block)
unsigned get_bit_block_COUNT_SUB_AB (bm::word_t *dst_block, bm::word_t *tmp_block)
unsigned get_bit_block_COUNT_SUB_BA (bm::word_t *dst_block, bm::word_t *tmp_block)
unsigned get_bit_block_COUNT_A (bm::word_t *dst_block, bm::word_t *tmp_block)
unsigned get_bit_block_COUNT_B (bm::word_t *dst_block, bm::word_t *tmp_block)
unsigned get_arr_bit (bm::word_t *dst_block, bool clear_target=true)
Get array of bits out of the decoder into bit block (Converts inverted list into bits) Returns number of words (bits) being read.
unsigned get_block_type () const
Get current block type.
unsigned get_bit ()
Protected Attributes
get_bit_func_type bit_func_table_ [bm::set_END]
decoder_type decoder_
bool end_of_stream_
unsigned bv_size_
iterator_state state_
unsigned id_cnt_
Id counter for id list.
bm::id_t last_id_
Last id from the id list.
gap_word_t glevels_ [bm::gap_levels]
GAP levels.
unsigned block_type_
current block type
unsigned block_idx_
current block index
unsigned mono_block_cnt_
number of 0 or 1 blocks
gap_word_t gap_head_
Protected Attributes inherited from bm::deseriaizer_base< DEC >
bm::gap_word_t id_array_ [bm::gap_equiv_len *2]
Additional Inherited Members
Protected Types inherited from bm::deseriaizer_base< DEC >
typedef DEC decoder_type
Protected Member Functions inherited from bm::deseriaizer_base< DEC >
deseriaizer_base ()
void read_gap_block (decoder_type &decoder, unsigned block_type, bm::gap_word_t *dst_block, bm::gap_word_t &gap_head)
Read GAP block from the stream.
unsigned read_id_list (decoder_type &decoder, unsigned block_type, bm::gap_word_t *dst_arr)
Read list of bit ids.
Detailed Description
template<class DEC>
class bm::serial_stream_iterator< DEC >
Serialization stream iterator.
Iterates blocks and control tokens of serialized bit-stream
Definition at line 397 of file bmserial.h.
Member Typedef Documentation
decoder_type
template<class DEC> typedef deseriaizer_base<DEC>::decoder_type bm::serial_stream_iterator< DEC >::decoder_type
Definition at line 400 of file bmserial.h.
get_bit_func_type
template<class DEC> typedef unsigned(serial_stream_iterator<DEC>::* bm::serial_stream_iterator< DEC >::get_bit_func_type) (bm::word_t *, bm::word_t *)
member function pointer for bitset-bitset get operations
Definition at line 464 of file bmserial.h.
Member Enumeration Documentation
iterator_state
template<class DEC> enum bm::serial_stream_iterator::iterator_state
iterator is a state machine, this enum encodes its key value
Enumerator
e_unknown
e_list_ids
plain int array
e_blocks
stream of blocks
e_zero_blocks
one or more zero bit blocks
e_one_blocks
one or more all-1 bit blocks
e_bit_block
one bit block
e_gap_block
one gap block
Definition at line 434 of file bmserial.h.
Constructor & Destructor Documentation
serial_stream_iterator()
template<class DEC > bm::serial_stream_iterator< DEC >::serial_stream_iterator (const unsigned char * buf)
Definition at line 1786 of file bmserial.h.
References bm::serial_stream_iterator< DEC >::bit_func_table_, bm::BM_HM_ID_LIST, bm::BM_HM_NO_BO, bm::BM_HM_NO_GAPL, bm::BM_HM_RESIZE, bm::serial_stream_iterator< DEC >::bv_size_, bm::serial_stream_iterator< DEC >::decoder_, bm::serial_stream_iterator< DEC >::e_blocks, bm::serial_stream_iterator< DEC >::e_list_ids, bm::gap_levels, bm::serial_stream_iterator< DEC >::glevels_, bm::serial_stream_iterator< DEC >::id_cnt_, bm::serial_stream_iterator< DEC >::next(), bm::set_AND, bm::set_ASSIGN, bm::set_COUNT, bm::set_COUNT_A, bm::set_COUNT_AND, bm::set_COUNT_B, bm::set_COUNT_OR, bm::set_COUNT_SUB_AB, bm::set_COUNT_SUB_BA, bm::set_COUNT_XOR, bm::set_OR, bm::set_SUB, bm::set_XOR, and bm::serial_stream_iterator< DEC >::state_.
Member Function Documentation
block_idx()
template<class DEC> unsigned bm::serial_stream_iterator< DEC >::block_idx () const inline
Get current block index.
Definition at line 457 of file bmserial.h.
bv_size()
template<class DEC> unsigned bm::serial_stream_iterator< DEC >::bv_size () const inline
serialized bitvector size
Definition at line 405 of file bmserial.h.
Referenced by bm::iterator_deserializer< BV, SerialIterator >::deserialize().
dec_size()
template<class DEC> unsigned bm::serial_stream_iterator< DEC >::dec_size () const inline
Return current decoder size.
Definition at line 426 of file bmserial.h.
decoder()
template<class DEC> decoder_type& bm::serial_stream_iterator< DEC >::decoder () inline
Get low level access to the decoder (use carefully)
Definition at line 429 of file bmserial.h.
get_arr_bit()
template<class DEC > unsigned bm::serial_stream_iterator< DEC >::get_arr_bit (bm::word_t * dst_block, bool clear_target = true)
Get array of bits out of the decoder into bit block (Converts inverted list into bits) Returns number of words (bits) being read.
Definition at line 2791 of file bmserial.h.
References bm::bit_block_set(), bm::serial_stream_iterator< DEC >::block_type_, BM_ASSERT, bm::serial_stream_iterator< DEC >::decoder_, and bm::set_bit().
Referenced by bm::serial_stream_iterator< DEC >::get_bit_block_AND(), bm::serial_stream_iterator< DEC >::get_bit_block_ASSIGN(), bm::serial_stream_iterator< DEC >::get_bit_block_COUNT(), bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_A(), bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_AND(), bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_OR(), bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_SUB_AB(), bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_SUB_BA(), bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_XOR(), bm::serial_stream_iterator< DEC >::get_bit_block_OR(), bm::serial_stream_iterator< DEC >::get_bit_block_SUB(), and bm::serial_stream_iterator< DEC >::get_bit_block_XOR().
get_bit()
template<class DEC > unsigned bm::serial_stream_iterator< DEC >::get_bit ()
Definition at line 2829 of file bmserial.h.
References bm::serial_stream_iterator< DEC >::block_idx_, bm::serial_stream_iterator< DEC >::block_type_, BM_ASSERT, bm::serial_stream_iterator< DEC >::decoder_, bm::serial_stream_iterator< DEC >::e_blocks, and bm::serial_stream_iterator< DEC >::state_.
get_bit_block()
template<class DEC > unsigned bm::serial_stream_iterator< DEC >::get_bit_block (bm::word_t * dst_block, bm::word_t * tmp_block, set_operation op)
read bit block, using logical operation
Definition at line 2858 of file bmserial.h.
References bm::serial_stream_iterator< DEC >::bit_func_table_, bm::serial_stream_iterator< DEC >::block_idx_, BM_ASSERT, bm::serial_stream_iterator< DEC >::e_bit_block, bm::serial_stream_iterator< DEC >::e_blocks, and bm::serial_stream_iterator< DEC >::state_.
get_bit_block_AND()
template<class DEC> unsigned bm::serial_stream_iterator< DEC >::get_bit_block_AND (bm::word_t * dst_block, bm::word_t * tmp_block)
Definition at line 2131 of file bmserial.h.
References bm::bit_block_and(), bm::serial_stream_iterator< DEC >::block_type_, BM_ASSERT, bm::serial_stream_iterator< DEC >::decoder_, bm::serial_stream_iterator< DEC >::e_bit_block, bm::serial_stream_iterator< DEC >::get_arr_bit(), bm::set_block_arrbit, bm::set_block_bit, bm::set_block_bit_0runs, bm::set_block_bit_1bit, bm::set_block_bit_interval, bm::set_block_size, and bm::serial_stream_iterator< DEC >::state_.
get_bit_block_ASSIGN()
template<class DEC > unsigned bm::serial_stream_iterator< DEC >::get_bit_block_ASSIGN (bm::word_t * dst_block, bm::word_t * tmp_block)
Definition at line 2015 of file bmserial.h.
References bm::bit_block_set(), bm::serial_stream_iterator< DEC >::block_type_, BM_ASSERT, bm::serial_stream_iterator< DEC >::decoder_, bm::serial_stream_iterator< DEC >::e_bit_block, bm::serial_stream_iterator< DEC >::get_arr_bit(), bm::set_block_arrbit, bm::set_block_bit, bm::set_block_bit_0runs, bm::set_block_bit_1bit, bm::set_block_bit_interval, bm::set_block_gapbit, bm::set_block_size, and bm::serial_stream_iterator< DEC >::state_.
get_bit_block_COUNT()
template<class DEC > unsigned bm::serial_stream_iterator< DEC >::get_bit_block_COUNT (bm::word_t * dst_block, bm::word_t * tmp_block)
Definition at line 2315 of file bmserial.h.
References bm::serial_stream_iterator< DEC >::block_type_, BM_ASSERT, bm::serial_stream_iterator< DEC >::decoder_, bm::serial_stream_iterator< DEC >::e_bit_block, bm::serial_stream_iterator< DEC >::get_arr_bit(), bm::set_block_arrbit, bm::set_block_bit, bm::set_block_bit_0runs, bm::set_block_bit_1bit, bm::set_block_bit_interval, bm::set_block_size, bm::serial_stream_iterator< DEC >::state_, and bm::word_bitcount().
get_bit_block_COUNT_A()
template<class DEC > unsigned bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_A (bm::word_t * dst_block, bm::word_t * tmp_block)
Definition at line 2372 of file bmserial.h.
References bm::bit_block_count(), bm::serial_stream_iterator< DEC >::block_type_, BM_ASSERT, bm::serial_stream_iterator< DEC >::decoder_, bm::serial_stream_iterator< DEC >::e_bit_block, bm::serial_stream_iterator< DEC >::get_arr_bit(), bm::set_block_arrbit, bm::set_block_bit, bm::set_block_bit_0runs, bm::set_block_bit_1bit, bm::set_block_bit_interval, bm::set_block_size, and bm::serial_stream_iterator< DEC >::state_.
get_bit_block_COUNT_AND()
template<class DEC > unsigned bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_AND (bm::word_t * dst_block, bm::word_t * tmp_block)
Definition at line 2433 of file bmserial.h.
References bm::bit_operation_and_count(), bm::serial_stream_iterator< DEC >::block_type_, BM_ASSERT, bm::serial_stream_iterator< DEC >::decoder_, bm::serial_stream_iterator< DEC >::e_bit_block, bm::serial_stream_iterator< DEC >::get_arr_bit(), bm::set_block_arrbit, bm::set_block_bit, bm::set_block_bit_0runs, bm::set_block_bit_1bit, bm::set_block_bit_interval, bm::set_block_size, bm::serial_stream_iterator< DEC >::state_, and bm::word_bitcount().
get_bit_block_COUNT_B()
template<class DEC> unsigned bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_B (bm::word_t * dst_block, bm::word_t * tmp_block) inline
Definition at line 491 of file bmserial.h.
get_bit_block_COUNT_OR()
template<class DEC > unsigned bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_OR (bm::word_t * dst_block, bm::word_t * tmp_block)
Definition at line 2491 of file bmserial.h.
References bm::bit_operation_or_count(), bm::bit_recomb(), bm::serial_stream_iterator< DEC >::block_type_, BM_ASSERT, bm::serial_stream_iterator< DEC >::decoder_, bm::serial_stream_iterator< DEC >::e_bit_block, bm::serial_stream_iterator< DEC >::get_arr_bit(), bm::set_block_arrbit, bm::set_block_bit, bm::set_block_bit_0runs, bm::set_block_bit_1bit, bm::set_block_bit_interval, bm::set_block_size, bm::serial_stream_iterator< DEC >::state_, bm::bitblock_sum_adapter::sum(), and bm::word_bitcount().
get_bit_block_COUNT_SUB_AB()
template<class DEC > unsigned bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_SUB_AB (bm::word_t * dst_block, bm::word_t * tmp_block)
Definition at line 2643 of file bmserial.h.
References bm::bit_operation_sub_count(), bm::bit_recomb(), bm::serial_stream_iterator< DEC >::block_type_, BM_ASSERT, bm::serial_stream_iterator< DEC >::decoder_, bm::serial_stream_iterator< DEC >::e_bit_block, bm::serial_stream_iterator< DEC >::get_arr_bit(), bm::set_block_arrbit, bm::set_block_bit, bm::set_block_bit_0runs, bm::set_block_bit_1bit, bm::set_block_bit_interval, bm::set_block_size, bm::serial_stream_iterator< DEC >::state_, bm::bitblock_sum_adapter::sum(), and bm::word_bitcount().
get_bit_block_COUNT_SUB_BA()
template<class DEC > unsigned bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_SUB_BA (bm::word_t * dst_block, bm::word_t * tmp_block)
Definition at line 2720 of file bmserial.h.
References bm::bit_operation_sub_count(), bm::bit_recomb(), bm::serial_stream_iterator< DEC >::block_type_, BM_ASSERT, bm::serial_stream_iterator< DEC >::decoder_, bm::serial_stream_iterator< DEC >::e_bit_block, bm::serial_stream_iterator< DEC >::get_arr_bit(), bm::set_block_arrbit, bm::set_block_bit, bm::set_block_bit_0runs, bm::set_block_bit_1bit, bm::set_block_bit_interval, bm::set_block_size, bm::serial_stream_iterator< DEC >::state_, bm::bitblock_sum_adapter::sum(), and bm::word_bitcount().
get_bit_block_COUNT_XOR()
template<class DEC > unsigned bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_XOR (bm::word_t * dst_block, bm::word_t * tmp_block)
Definition at line 2567 of file bmserial.h.
References bm::bit_operation_xor_count(), bm::bit_recomb(), bm::serial_stream_iterator< DEC >::block_type_, BM_ASSERT, bm::serial_stream_iterator< DEC >::decoder_, bm::serial_stream_iterator< DEC >::e_bit_block, bm::serial_stream_iterator< DEC >::get_arr_bit(), bm::set_block_arrbit, bm::set_block_bit, bm::set_block_bit_0runs, bm::set_block_bit_1bit, bm::set_block_bit_interval, bm::set_block_size, bm::serial_stream_iterator< DEC >::state_, bm::bitblock_sum_adapter::sum(), and bm::word_bitcount().
get_bit_block_OR()
template<class DEC > unsigned bm::serial_stream_iterator< DEC >::get_bit_block_OR (bm::word_t * dst_block, bm::word_t * tmp_block)
Definition at line 2079 of file bmserial.h.
References bm::serial_stream_iterator< DEC >::block_type_, BM_ASSERT, bm::serial_stream_iterator< DEC >::decoder_, bm::serial_stream_iterator< DEC >::e_bit_block, bm::serial_stream_iterator< DEC >::get_arr_bit(), bm::set_block_arrbit, bm::set_block_bit, bm::set_block_bit_0runs, bm::set_block_bit_1bit, bm::set_block_bit_interval, bm::set_block_size, and bm::serial_stream_iterator< DEC >::state_.
get_bit_block_SUB()
template<class DEC > unsigned bm::serial_stream_iterator< DEC >::get_bit_block_SUB (bm::word_t * dst_block, bm::word_t * tmp_block)
Definition at line 2256 of file bmserial.h.
References bm::bit_block_sub(), bm::serial_stream_iterator< DEC >::block_type_, BM_ASSERT, bm::serial_stream_iterator< DEC >::decoder_, bm::serial_stream_iterator< DEC >::e_bit_block, bm::serial_stream_iterator< DEC >::get_arr_bit(), bm::set_block_arrbit, bm::set_block_bit, bm::set_block_bit_0runs, bm::set_block_bit_1bit, bm::set_block_bit_interval, bm::set_block_size, and bm::serial_stream_iterator< DEC >::state_.
get_bit_block_XOR()
template<class DEC > unsigned bm::serial_stream_iterator< DEC >::get_bit_block_XOR (bm::word_t * dst_block, bm::word_t * tmp_block)
Definition at line 2196 of file bmserial.h.
References bm::bit_block_xor(), bm::serial_stream_iterator< DEC >::block_type_, BM_ASSERT, bm::serial_stream_iterator< DEC >::decoder_, bm::serial_stream_iterator< DEC >::e_bit_block, bm::serial_stream_iterator< DEC >::get_arr_bit(), bm::set_block_arrbit, bm::set_block_bit, bm::set_block_bit_0runs, bm::set_block_bit_1bit, bm::set_block_bit_interval, bm::set_block_size, and bm::serial_stream_iterator< DEC >::state_.
get_block_type()
template<class DEC> unsigned bm::serial_stream_iterator< DEC >::get_block_type () const inline
Get current block type.
Definition at line 503 of file bmserial.h.
get_gap_block()
template<class DEC > void bm::serial_stream_iterator< DEC >::get_gap_block (bm::gap_word_t * dst_block)
Read gap block data (with head)
Definition at line 2840 of file bmserial.h.
References bm::serial_stream_iterator< DEC >::block_idx_, bm::serial_stream_iterator< DEC >::block_type_, BM_ASSERT, bm::serial_stream_iterator< DEC >::decoder_, bm::serial_stream_iterator< DEC >::e_blocks, bm::serial_stream_iterator< DEC >::e_gap_block, bm::serial_stream_iterator< DEC >::gap_head_, bm::deseriaizer_base< DEC >::read_gap_block(), and bm::serial_stream_iterator< DEC >::state_.
get_id()
template<class DEC> bm::id_t bm::serial_stream_iterator< DEC >::get_id () const inline
Get last id from the id list.
Definition at line 454 of file bmserial.h.
get_id_count()
template<class DEC> unsigned bm::serial_stream_iterator< DEC >::get_id_count () const inline
Number of ids in the inverted list (valid for e_list_ids)
Definition at line 451 of file bmserial.h.
get_state()
template<class DEC> iterator_state bm::serial_stream_iterator< DEC >::get_state () const inline
Definition at line 449 of file bmserial.h.
is_eof()
template<class DEC> bool bm::serial_stream_iterator< DEC >::is_eof () const inline
Returns true if end of bit-stream reached.
Definition at line 408 of file bmserial.h.
Referenced by bm::serial_stream_iterator< DEC >::next().
next()
template<class DEC > void bm::serial_stream_iterator< DEC >::next ()
get next block
Definition at line 1867 of file bmserial.h.
References bm::serial_stream_iterator< DEC >::block_idx_, bm::serial_stream_iterator< DEC >::block_type_, BM_ASSERT, bm::serial_stream_iterator< DEC >::decoder_, bm::serial_stream_iterator< DEC >::e_bit_block, bm::serial_stream_iterator< DEC >::e_blocks, bm::serial_stream_iterator< DEC >::e_gap_block, bm::serial_stream_iterator< DEC >::e_list_ids, bm::serial_stream_iterator< DEC >::e_one_blocks, bm::serial_stream_iterator< DEC >::e_unknown, bm::serial_stream_iterator< DEC >::e_zero_blocks, bm::serial_stream_iterator< DEC >::end_of_stream_, bm::serial_stream_iterator< DEC >::gap_head_, bm::serial_stream_iterator< DEC >::id_cnt_, bm::serial_stream_iterator< DEC >::is_eof(), bm::serial_stream_iterator< DEC >::last_id_, bm::serial_stream_iterator< DEC >::mono_block_cnt_, bm::set_block_16one, bm::set_block_16zero, bm::set_block_1one, bm::set_block_1zero, bm::set_block_32one, bm::set_block_32zero, bm::set_block_8one, bm::set_block_8zero, bm::set_block_aone, bm::set_block_arrbit, bm::set_block_arrgap, bm::set_block_arrgap_egamma, bm::set_block_arrgap_egamma_inv, bm::set_block_arrgap_inv, bm::set_block_azero, bm::set_block_bit, bm::set_block_bit_0runs, bm::set_block_bit_1bit, bm::set_block_bit_interval, bm::set_block_end, bm::set_block_gap, bm::set_block_gap_egamma, bm::set_block_gapbit, bm::set_total_blocks, and bm::serial_stream_iterator< DEC >::state_.
Referenced by bm::serial_stream_iterator< DEC >::serial_stream_iterator().
skip_mono_blocks()
template<class DEC > void bm::serial_stream_iterator< DEC >::skip_mono_blocks ()
skip all zero or all-one blocks
Definition at line 1998 of file bmserial.h.
References bm::serial_stream_iterator< DEC >::block_idx_, BM_ASSERT, bm::serial_stream_iterator< DEC >::e_blocks, bm::serial_stream_iterator< DEC >::e_one_blocks, bm::serial_stream_iterator< DEC >::e_zero_blocks, bm::serial_stream_iterator< DEC >::mono_block_cnt_, and bm::serial_stream_iterator< DEC >::state_.
state()
template<class DEC> iterator_state bm::serial_stream_iterator< DEC >::state () const inline
Returns iterator internal state.
Definition at line 447 of file bmserial.h.
Referenced by bm::iterator_deserializer< BV, SerialIterator >::deserialize().
Field Documentation
bit_func_table_
template<class DEC> get_bit_func_type bm::serial_stream_iterator< DEC >::bit_func_table_[bm::set_END] protected
Definition at line 508 of file bmserial.h.
Referenced by bm::serial_stream_iterator< DEC >::get_bit_block(), and bm::serial_stream_iterator< DEC >::serial_stream_iterator().
block_idx_
template<class DEC> unsigned bm::serial_stream_iterator< DEC >::block_idx_ protected
current block index
Definition at line 519 of file bmserial.h.
Referenced by bm::serial_stream_iterator< DEC >::get_bit(), bm::serial_stream_iterator< DEC >::get_bit_block(), bm::serial_stream_iterator< DEC >::get_gap_block(), bm::serial_stream_iterator< DEC >::next(), and bm::serial_stream_iterator< DEC >::skip_mono_blocks().
block_type_
template<class DEC> unsigned bm::serial_stream_iterator< DEC >::block_type_ protected
current block type
Definition at line 518 of file bmserial.h.
Referenced by bm::serial_stream_iterator< DEC >::get_arr_bit(), bm::serial_stream_iterator< DEC >::get_bit(), bm::serial_stream_iterator< DEC >::get_bit_block_AND(), bm::serial_stream_iterator< DEC >::get_bit_block_ASSIGN(), bm::serial_stream_iterator< DEC >::get_bit_block_COUNT(), bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_A(), bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_AND(), bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_OR(), bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_SUB_AB(), bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_SUB_BA(), bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_XOR(), bm::serial_stream_iterator< DEC >::get_bit_block_OR(), bm::serial_stream_iterator< DEC >::get_bit_block_SUB(), bm::serial_stream_iterator< DEC >::get_bit_block_XOR(), bm::serial_stream_iterator< DEC >::get_gap_block(), and bm::serial_stream_iterator< DEC >::next().
bv_size_
template<class DEC> unsigned bm::serial_stream_iterator< DEC >::bv_size_ protected
Definition at line 512 of file bmserial.h.
Referenced by bm::serial_stream_iterator< DEC >::serial_stream_iterator().
decoder_
template<class DEC> decoder_type bm::serial_stream_iterator< DEC >::decoder_ protected
Definition at line 510 of file bmserial.h.
Referenced by bm::serial_stream_iterator< DEC >::get_arr_bit(), bm::serial_stream_iterator< DEC >::get_bit(), bm::serial_stream_iterator< DEC >::get_bit_block_AND(), bm::serial_stream_iterator< DEC >::get_bit_block_ASSIGN(), bm::serial_stream_iterator< DEC >::get_bit_block_COUNT(), bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_A(), bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_AND(), bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_OR(), bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_SUB_AB(), bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_SUB_BA(), bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_XOR(), bm::serial_stream_iterator< DEC >::get_bit_block_OR(), bm::serial_stream_iterator< DEC >::get_bit_block_SUB(), bm::serial_stream_iterator< DEC >::get_bit_block_XOR(), bm::serial_stream_iterator< DEC >::get_gap_block(), bm::serial_stream_iterator< DEC >::next(), and bm::serial_stream_iterator< DEC >::serial_stream_iterator().
end_of_stream_
template<class DEC> bool bm::serial_stream_iterator< DEC >::end_of_stream_ protected
Definition at line 511 of file bmserial.h.
Referenced by bm::serial_stream_iterator< DEC >::next().
gap_head_
template<class DEC> gap_word_t bm::serial_stream_iterator< DEC >::gap_head_ protected
Definition at line 522 of file bmserial.h.
Referenced by bm::serial_stream_iterator< DEC >::get_gap_block(), and bm::serial_stream_iterator< DEC >::next().
glevels_
template<class DEC> gap_word_t bm::serial_stream_iterator< DEC >::glevels_[bm::gap_levels] protected
GAP levels.
Definition at line 516 of file bmserial.h.
Referenced by bm::serial_stream_iterator< DEC >::serial_stream_iterator().
id_cnt_
template<class DEC> unsigned bm::serial_stream_iterator< DEC >::id_cnt_ protected
Id counter for id list.
Definition at line 514 of file bmserial.h.
Referenced by bm::serial_stream_iterator< DEC >::next(), and bm::serial_stream_iterator< DEC >::serial_stream_iterator().
last_id_
template<class DEC> bm::id_t bm::serial_stream_iterator< DEC >::last_id_ protected
Last id from the id list.
Definition at line 515 of file bmserial.h.
Referenced by bm::serial_stream_iterator< DEC >::next().
mono_block_cnt_
template<class DEC> unsigned bm::serial_stream_iterator< DEC >::mono_block_cnt_ protected
number of 0 or 1 blocks
Definition at line 520 of file bmserial.h.
Referenced by bm::serial_stream_iterator< DEC >::next(), and bm::serial_stream_iterator< DEC >::skip_mono_blocks().
state_
template<class DEC> iterator_state bm::serial_stream_iterator< DEC >::state_ protected
Definition at line 513 of file bmserial.h.
Referenced by bm::serial_stream_iterator< DEC >::get_bit(), bm::serial_stream_iterator< DEC >::get_bit_block(), bm::serial_stream_iterator< DEC >::get_bit_block_AND(), bm::serial_stream_iterator< DEC >::get_bit_block_ASSIGN(), bm::serial_stream_iterator< DEC >::get_bit_block_COUNT(), bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_A(), bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_AND(), bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_OR(), bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_SUB_AB(), bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_SUB_BA(), bm::serial_stream_iterator< DEC >::get_bit_block_COUNT_XOR(), bm::serial_stream_iterator< DEC >::get_bit_block_OR(), bm::serial_stream_iterator< DEC >::get_bit_block_SUB(), bm::serial_stream_iterator< DEC >::get_bit_block_XOR(), bm::serial_stream_iterator< DEC >::get_gap_block(), bm::serial_stream_iterator< DEC >::next(), bm::serial_stream_iterator< DEC >::serial_stream_iterator(), and bm::serial_stream_iterator< DEC >::skip_mono_blocks().
The documentation for this class was generated from the following file:
bmserial.h