BitMagic-C++: sample7.cpp File Reference
sample7.cpp File Reference
Example: set operations between bvector<> and arrays of integers.
#include <iostream>
#include <algorithm>
#include <vector>
#include <list>
#include "bm.h"
#include "bmalgo.h"
Functions
void Print (unsigned n)
template<class T >
void PrintContainer (T first, T last)
int main (void)
Detailed Description
Example: set operations between bvector<> and arrays of integers.
Definition in file sample7.cpp.
Function Documentation
main()
int main (void)
Examples:
sample7.cpp.
Definition at line 72 of file sample7.cpp.
References bm::bvector< Alloc >::clear(), bm::combine_and(), bm::combine_and_sorted(), bm::combine_or(), bm::combine_sub(), bm::bvector< Alloc >::end(), bm::bvector< Alloc >::first(), and PrintContainer().
Print()
void Print (unsigned n) inline
Examples:
sample7.cpp.
Definition at line 56 of file sample7.cpp.
PrintContainer()
template<class T > void PrintContainer (T first, T last)
Examples:
sample7.cpp.
Definition at line 62 of file sample7.cpp.
Referenced by main().