BitMagic-C++: sample14.cpp File Reference
sample14.cpp File Reference
Example: bvector<> set operations on serialized/compressed BLOBs.
#include <stdlib.h>
#include <iostream>
#include <vector>
#include "bm.h"
#include "bmserial.h"
Functions
static void fill_bvector (bm::bvector<> *bv)
int main (void)
Variables
const unsigned MAX_VALUE = 1000000
Detailed Description
Example: bvector<> set operations on serialized/compressed BLOBs.
Definition in file sample14.cpp.
Function Documentation
fill_bvector()
static void fill_bvector (bm::bvector<> * bv) static
Examples:
sample14.cpp.
Definition at line 47 of file sample14.cpp.
References MAX_VALUE, and bm::bvector< Alloc >::set().
Referenced by main().
main()
int main (void)
Examples:
sample14.cpp.
Definition at line 59 of file sample14.cpp.
References BM_DECLARE_TEMP_BLOCK, bm::bvector< Alloc >::compare(), bm::bvector< Alloc >::count(), bm::deserialize(), fill_bvector(), bm::bvector< Alloc >::optimize(), bm::serializer< BV >::serialize(), bm::set_AND, bm::serializer< BV >::set_compression_level(), bm::set_COUNT_SUB_AB, and bm::set_SUB.
Variable Documentation
MAX_VALUE
const unsigned MAX_VALUE = 1000000
Examples:
sample14.cpp.
Definition at line 44 of file sample14.cpp.
Referenced by fill_bvector().