BitMagic-C++: sample3.cpp File Reference
sample3.cpp File Reference
Example: bvector<> with different allocation/compression strategies.
#include <stdlib.h>
#include <iostream>
#include "bm.h"
Functions
static void fill_bvector (bm::bvector<> *bv1, bm::bvector<> *bv2)
static void print_statistics (const bm::bvector<> &bv)
int main (void)
Variables
const unsigned MAX_VALUE = 1000000
Detailed Description
Example: bvector<> with different allocation/compression strategies.
Definition in file sample3.cpp.
Function Documentation
fill_bvector()
static void fill_bvector (bm::bvector<> * bv1, bm::bvector<> * bv2) static
Examples:
sample3.cpp.
Definition at line 47 of file sample3.cpp.
References MAX_VALUE, and bm::bvector< Alloc >::set_bit().
Referenced by main().
main()
int main (void)
Examples:
sample3.cpp.
Definition at line 73 of file sample3.cpp.
References bm::BM_GAP, fill_bvector(), bm::bvector< Alloc >::optimize(), print_statistics(), and bm::bvector< Alloc >::set_new_blocks_strat().
print_statistics()
static void print_statistics (const bm::bvector<> & bv) static
Examples:
sample3.cpp.
Definition at line 60 of file sample3.cpp.
References bm::bv_statistics::bit_blocks, bm::bvector< Alloc >::calc_stat(), bm::bvector< Alloc >::count(), bm::bv_statistics::gap_blocks, bm::bv_statistics::max_serialize_mem, and bm::bv_statistics::memory_used.
Referenced by main().
Variable Documentation
MAX_VALUE
const unsigned MAX_VALUE = 1000000
Examples:
sample3.cpp.
Definition at line 41 of file sample3.cpp.
Referenced by fill_bvector().