BitMagic-C++: sample9.cpp File Reference
sample9.cpp File Reference
Example: bvector<> binary similarity / distance algorithms.
#include <iostream>
#include "bm.h"
#include "bmalgo.h"
Functions
int main (void)
Detailed Description
Example: bvector<> binary similarity / distance algorithms.
Definition in file sample9.cpp.
Function Documentation
main()
int main (void)
Examples:
sample9.cpp.
Definition at line 47 of file sample9.cpp.
References bm::bvector< Alloc >::count(), bm::COUNT_A, bm::COUNT_AND, bm::count_and(), bm::COUNT_B, bm::count_xor(), bm::distance_operation(), and bm::distance_metric_descriptor::metric.