BitMagic-C++: sample2.cpp File Reference
sample2.cpp File Reference
Example: bvector<> set algebra operations AND, OR, XOR, etc.
#include <iostream>
#include "bm.h"
Functions
static void print_bvector (const bm::bvector<> &bv)
int main (void)
Detailed Description
Example: bvector<> set algebra operations AND, OR, XOR, etc.
Definition in file sample2.cpp.
Function Documentation
main()
int main (void)
Examples:
sample2.cpp.
Definition at line 54 of file sample2.cpp.
References print_bvector(), and bm::bvector< Alloc >::set().
print_bvector()
static void print_bvector (const bm::bvector<> & bv) static
Examples:
sample2.cpp.
Definition at line 35 of file sample2.cpp.
References bm::bvector< Alloc >::get_first(), and bm::bvector< Alloc >::get_next().
Referenced by main().