BitMagic-C++: sample15.cpp File Reference
sample15.cpp File Reference
Example: bvector<> methods to find last bit and bit-vectors effective range.
#include <stdlib.h>
#include <iostream>
#include <vector>
#include "bm.h"
Functions
static void fill_bvector (bm::bvector<> *bv)
int main (void)
Variables
const unsigned MAX_VALUE = 10000000
Detailed Description
Example: bvector<> methods to find last bit and bit-vectors effective range.
Definition in file sample15.cpp.
Function Documentation
fill_bvector()
static void fill_bvector (bm::bvector<> * bv) static
Examples:
sample15.cpp.
Definition at line 47 of file sample15.cpp.
References MAX_VALUE, and bm::bvector< Alloc >::set().
Referenced by main().
main()
int main (void)
Examples:
sample15.cpp.
Definition at line 60 of file sample15.cpp.
References bm::bvector< Alloc >::count(), fill_bvector(), bm::bvector< Alloc >::find(), bm::bvector< Alloc >::find_range(), and bm::bvector< Alloc >::find_reverse().
Variable Documentation
MAX_VALUE
const unsigned MAX_VALUE = 10000000
Examples:
sample15.cpp.
Definition at line 44 of file sample15.cpp.
Referenced by fill_bvector().