BitMagic-C++: strsvsample01.cpp File Reference
strsvsample01.cpp File Reference
Example: str_sparse_vector<> set values, optimize memory.
#include <iostream>
#include <string>
#include <vector>
#include "bmstrsparsevec.h"
Typedefs
typedef bm::bvector bvector_type
typedef bm::str_sparse_vector< char, bvector_type, 32 > str_sv_type
Functions
int main (void)
Detailed Description
Example: str_sparse_vector<> set values, optimize memory.
Definition in file strsvsample01.cpp.
Typedef Documentation
bvector_type
typedef bm::bvector bvector_type
Definition at line 37 of file strsvsample01.cpp.
str_sv_type
typedef bm::str_sparse_vector<char, bvector_type, 32> str_sv_type
Definition at line 45 of file strsvsample01.cpp.
Function Documentation
main()
int main (void)
Definition at line 47 of file strsvsample01.cpp.
References bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::assign(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::begin(), BM_DECLARE_TEMP_BLOCK, bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::end(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::optimize(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::push_back(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::set(), and bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::size().