BitMagic-C++: strsvsample03.cpp File Reference
strsvsample03.cpp File Reference
#include <iostream>
#include <string>
#include <vector>
#include <random>
#include <algorithm>
#include <fstream>
#include "bmstrsparsevec.h"
#include "bmsparsevec_serial.h"
Typedefs
typedef bm::bvector bvector_type
typedef bm::str_sparse_vector< char, bvector_type, 32 > str_sv_type
Functions
static void generate_string_set (vector< string > &str_vec)
int main (void)
Typedef Documentation
bvector_type
typedef bm::bvector bvector_type
Definition at line 45 of file strsvsample03.cpp.
str_sv_type
typedef bm::str_sparse_vector<char, bvector_type, 32> str_sv_type
Definition at line 53 of file strsvsample03.cpp.
Function Documentation
generate_string_set()
static void generate_string_set (vector< string > & str_vec) static
Definition at line 59 of file strsvsample03.cpp.
Referenced by main().
main()
int main (void)
Definition at line 79 of file strsvsample03.cpp.
References BM_DECLARE_TEMP_BLOCK, bm::sparse_vector_serial_layout< SV >::buf(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::back_insert_iterator::flush(), generate_string_set(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::get_back_inserter(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::optimize(), bm::str_sparse_vector< CharType, BV, MAX_STR_SIZE >::remap_from(), bm::sparse_vector_serial_layout< SV >::size(), and bm::sparse_vector_serialize().