BitMagic-C++: bm::globals< T > Struct Template Reference
bm::globals< T > Struct Template Reference
Internal structure.
#include <bmconst.h>
Data Structures
struct bo
Static Public Member Functions
static ByteOrder byte_order ()
Static Public Attributes
static bo _bo
Detailed Description
template<bool T>
struct bm::globals< T >
Internal structure.
Different global settings.
Definition at line 415 of file bmconst.h.
Member Function Documentation
byte_order()
template<bool T> static ByteOrder bm::globals< T >::byte_order () inline static
Definition at line 441 of file bmconst.h.
References bm::globals< T >::bo::_byte_order.
Referenced by bm::operation_deserializer< BV >::deserialize(), bm::sparse_vector_serializer< SV >::serialize(), and bm::compressed_collection_serializer< CBC >::serialize().
Field Documentation
_bo
template<bool T> globals< T >::bo bm::globals< T >::_bo static
Definition at line 440 of file bmconst.h.
The documentation for this struct was generated from the following file:
bmconst.h