BitMagic-C++: bm::operation_functions< T > Struct Template Reference
bm::operation_functions< T > Struct Template Reference
#include <bmfunc.h>
Static Public Member Functions
static gap_operation_to_bitset_func_type gap_op_to_bit (unsigned i)
static gap_operation_func_type gap_operation (unsigned i)
static bit_operation_count_func_type bit_operation_count (unsigned i)
Static Public Attributes
static gap_operation_to_bitset_func_type gap2bit_table_ [bm::set_END]
static gap_operation_func_type gapop_table_ [bm::set_END]
static bit_operation_count_func_type bit_op_count_table_ [bm::set_END]
Detailed Description
template<bool T>
struct bm::operation_functions< T >
Definition at line 6978 of file bmfunc.h.
Member Function Documentation
bit_operation_count()
template<bool T> static bit_operation_count_func_type bm::operation_functions< T >::bit_operation_count (unsigned i) inline static
Definition at line 7000 of file bmfunc.h.
References bm::bit_operation_and_count(), bm::bit_operation_or_count(), bm::bit_operation_sub_count(), bm::bit_operation_sub_count_inv(), bm::bit_operation_xor_count(), bm::gap_operation_and(), bm::gap_operation_or(), bm::gap_operation_sub(), bm::gap_operation_xor(), and bm::set_END.
Referenced by bm::combine_count_operation_with_block().
gap_op_to_bit()
template<bool T> static gap_operation_to_bitset_func_type bm::operation_functions< T >::gap_op_to_bit (unsigned i) inline static
Definition at line 6988 of file bmfunc.h.
Referenced by bm::bvector<>::combine_operation().
gap_operation()
template<bool T> static gap_operation_func_type bm::operation_functions< T >::gap_operation (unsigned i) inline static
Definition at line 6994 of file bmfunc.h.
Referenced by bm::bvector<>::combine_operation().
Field Documentation
bit_op_count_table_
template<bool T> bit_operation_count_func_type bm::operation_functions< T >::bit_op_count_table_ static
Initial value:
= {
    0,
    0,
    0,
    0,
    0,
    0,
    &bit_operation_and_count,
    &bit_operation_xor_count,
    &bit_operation_or_count,
    &bit_operation_sub_count,
    &bit_operation_sub_count_inv,
    0,
    0,
}
Definition at line 6985 of file bmfunc.h.
gap2bit_table_
template<bool T> gap_operation_to_bitset_func_type bm::operation_functions< T >::gap2bit_table_ static
Initial value:
= {
    &gap_and_to_bitset<bm::gap_word_t>,
    &gap_add_to_bitset<bm::gap_word_t>,
    &gap_sub_to_bitset<bm::gap_word_t>,
    &gap_xor_to_bitset<bm::gap_word_t>,
    0
}
Definition at line 6981 of file bmfunc.h.
gapop_table_
template<bool T> gap_operation_func_type bm::operation_functions< T >::gapop_table_ static
Initial value:
= {
    &gap_operation_and,
    &gap_operation_or,
    &gap_operation_sub,
    &gap_operation_xor,
    0
}
Definition at line 6983 of file bmfunc.h.
The documentation for this struct was generated from the following file:
bmfunc.h