BitMagic-C++: svsample04.cpp File Reference
svsample04.cpp File Reference
Example: sparse_vector<> with NULL (unset) values.
#include <iostream>
#include <vector>
#include "bmsparsevec.h"
Functions
static void print_svector (const bm::sparse_vector< unsigned, bm::bvector<> > &sv)
int main (void)
Detailed Description
Example: sparse_vector<> with NULL (unset) values.
Definition in file svsample04.cpp.
Function Documentation
main()
int main (void)
Examples:
svsample04.cpp.
Definition at line 62 of file svsample04.cpp.
References bm::sparse_vector< Val, BV >::clear(), bm::sparse_vector< Val, BV >::decode(), bm::bvector< Alloc >::first(), bm::base_sparse_vector< Val, BV, 1 >::get_null_bvector(), bm::sparse_vector< Val, BV >::import(), bm::sparse_vector< Val, BV >::join(), print_svector(), bm::sparse_vector< Val, BV >::push_back(), bm::sparse_vector< Val, BV >::resize(), bm::sparse_vector< Val, BV >::set(), bm::sparse_vector< Val, BV >::set_null(), bm::sparse_vector< Val, BV >::size(), bm::use_null, and bm::bvector< Alloc >::iterator_base::valid().
print_svector()
static void print_svector (const bm::sparse_vector< unsigned, bm::bvector<> > & sv) static
Definition at line 36 of file svsample04.cpp.
Referenced by main().