BitMagic-C++: svsample03.cpp File Reference
svsample03.cpp File Reference
Example: sparse_vector<> merge and fast extraction of content.
#include <iostream>
#include <vector>
#include "bmsparsevec.h"
Functions
int main (void)
Detailed Description
Example: sparse_vector<> merge and fast extraction of content.
Definition in file svsample03.cpp.
Function Documentation
main()
int main (void)
Examples:
svsample03.cpp.
Definition at line 39 of file svsample03.cpp.
References bm::sparse_vector< Val, BV >::at(), BM_DECLARE_TEMP_BLOCK, bm::sparse_vector< Val, BV >::decode(), bm::sparse_vector< Val, BV >::import(), bm::sparse_vector< Val, BV >::join(), bm::sparse_vector< Val, BV >::optimize(), bm::sparse_vector< Val, BV >::set(), and bm::sparse_vector< Val, BV >::size().