BitMagic-C++: svsample02.cpp File Reference
svsample02.cpp File Reference
Example: sparse_vector<> serialization.
#include <iostream>
#include <vector>
#include "bmsparsevec.h"
#include "bmsparsevec_serial.h"
Typedefs
typedef bm::sparse_vector< unsigned, bm::bvector<> > svector
Functions
int main (void)
Detailed Description
Example: sparse_vector<> serialization.
Definition in file svsample02.cpp.
Typedef Documentation
svector
typedef bm::sparse_vector<unsigned, bm::bvector<> > svector
Examples:
svsample02.cpp.
Definition at line 42 of file svsample02.cpp.
Function Documentation
main()
int main (void)
Examples:
svsample02.cpp.
Definition at line 44 of file svsample02.cpp.
References BM_DECLARE_TEMP_BLOCK, bm::sparse_vector_serial_layout< SV >::buf(), bm::sparse_vector< Val, BV >::equal(), bm::sparse_vector< Val, BV >::optimize(), bm::sparse_vector< Val, BV >::push_back(), bm::sparse_vector_serial_layout< SV >::size(), bm::sparse_vector< Val, BV >::size(), bm::sparse_vector_deserialize(), and bm::sparse_vector_serialize().